<?php
defined('BASEPATH') or exit('No direct script access allowed');
include APPPATH . '/libraries/CommonTrait.php';

class ADCController extends CI_Controller
{
    use CommonTrait;

    const AADHAAR_CONSENT_CONTENT = ' <p>I hereby give my consent for using my identity and address data received from e-KYC provider to generate and submit the electronic DSC application form to CA, creation of key pairs by ESP on my behalf, submission of certificate to CA for certification, one time creation of signature on the hash along with this request, deletion of key pairs after applyingsignature(s). I have noobjection in the use of my ID for authenticating myself with Aadhaar based authentication system for the purposes of availing of the eCabinet from Home & Political Department, Government of Assam. I understand that the Biometrics and/or OTP I provide for authentication shall be used only for authenticating my identity through the Aadhaar Authentication system, for obtaining my e-KYC through Aadhaar e-KYC service and for the issuance of Digital Signature Certificate (DSC) for this specific transaction and for no other purposes.For the creation of DSC, I understand that the options that I have chosen are the ones that shall be populated in the DSC generated by the CA and I provide my consent for the same. I also understand that the following fields in the DSC generated by the CA are mandatory and I give my consent for using the Aadhaar provided e-KYC information to populate the corresponding fields in the DSC.</p><p>Common Name (name as obtained from e-KYC), Unique Identifier (UID Token), Pseudonym (unique code sent by UIDAI in e-KYC response), State or Province (state as obtained from e-KYC), Postal Code (postal code as obtained from e-KYC)</p>';

    const AADHAAR_CONSENT_CHECKBOX_TEXT = 'I understand that Home & Political Department, Government of Assam shall ensure security and confidentiality of my personal identity data provided for the purpose of Aadhaar based authentication.';

    function __construct()
    {
        parent::__construct();
        $this->load->model('UserModel');
        $this->load->model('Chithamodel');
        $this->load->model('MisModel');
        $this->load->model('LoginModel');
        $this->load->helper(array('form', 'url'));
        $this->load->library('form_validation');
        $this->load->helper('security');
        $this->load->helper('language');
        $district_code = $this->session->userdata('dist_code');
        if (in_array($district_code, BARAK_VALLEY)) {
            $this->lang->load("bengali", "bengali");
        } else {
            $this->lang->load("assamese", "assamese");
        }
    }
    public function index()
    {
        $this->dataswitch();
        // dd($this->session->userdata);
        $dist_code = $this->session->userdata('dist_code');
        $data['page_header'] = 'Chitha Verification';

        // $subdivs_arr = $this->db->query("SELECT distinct subdiv_code, cir_code
        //                         FROM alloted_dags
        //                         WHERE dist_code = '$dist_code'
        //                             AND subdiv_code != '00'
        //                             AND cir_code != '00'
        //                             AND mouza_pargona_code !='00'
        //                             AND lot_no!='00'
        //                             AND vill_townprt_code != '00000'
        //                             -- AND vill_townprt_code != '00000'
        //                             AND is_signed = 1
        //                             AND user_desig_code = 'CO'")->result_array();
        
        // $subdivs = $circodes = '';
        // if(count($subdivs_arr) > 0){
        //     $subdiv_array = $cir_code_array = [];
        //     foreach($subdivs_arr as $subdiv_arr){
        //         $conditions = [
        //                         'dist_code' => $dist_code,
        //                         'subdiv_code' => $subdiv_arr['subdiv_code'],
        //                         'cir_code' => $subdiv_arr['cir_code'],
        //                         'user_desig_code' => 'CO'
        //                     ];
        //         $alloted_dags = $this->db->where($conditions)
        //                                     ->get('alloted_dags')
        //                                     ->num_rows();
                
        //         $signed_alloted_dags = $this->db->where($conditions)
        //                                     ->where('is_signed', 1)
        //                                     ->get('alloted_dags')
        //                                     ->num_rows();
                
        //         if($alloted_dags > 0 && $alloted_dags == $signed_alloted_dags){
        //             $subdiv_array[] = "'" . $subdiv_arr['subdiv_code'] . "'";
        //             $cir_code_array[] = "'" . $subdiv_arr['cir_code'] . "'";
        //         }

        //     }

        //     $subdivs = implode(',', $subdiv_array);
        //     $circodes = implode(',', $cir_code_array);
        // }
        
        // if($subdivs != '' && $circodes != ''){
        //     $query = "select * from location l where l.dist_code=? and l.subdiv_code in ($subdivs) and l.cir_code in ($circodes) and l.mouza_pargona_code = '00' and l.lot_no = '00' and l.vill_townprt_code = '00000'";
        //     $data['circles'] = $this->db->query($query, $dist_code)->result_array();
        // }else{
        //     $data['circles'] = [];
        // }

        $circles = $this->db->query("SELECT * FROM location WHERE dist_code=? AND subdiv_code!='00' AND cir_code!='00' AND mouza_pargona_code='00' AND lot_no='00' AND vill_townprt_code='00000'", [$dist_code])->result_array();

        $data['circles'] = $circles;
        
        $data['_view'] = 'verification/adc/dashboard';
        $this->load->view('layout/layout', $data);
    }

    public function getMouzas() {
        if(!isset($_POST['cir_code']) || $_POST['cir_code'] == '') {
            echo json_encode([
                'status'=>'FAILED',
                'responseType'=>1,
                'msg'=>'Input Parameters are not set'
            ]);
            exit();
        }
        $sessionData = $this->session->all_userdata();
        if(!$sessionData) {
            echo json_encode([
                'status'=>'FAILED',
                'responseType'=>1,
                'msg'=>'Session is expired. Please login again.'
            ]);
            exit();
        }
        $dist_code = $this->session->userdata('dcode');
        $subdiv_cir_code = explode('_', $this->input->post('cir_code'));
        $subdiv_code = $subdiv_cir_code[0];
        $cir_code = $subdiv_cir_code[1];

        $this->dataswitch();

        $mouzas = $this->Chithamodel->mouzadetails($dist_code, $subdiv_code, $cir_code);

        echo json_encode([
            'status'=>'SUCCESS',
            'responseType'=>2,
            'msg'=>'',
            'data'=>$mouzas
        ]);
        exit();
    }

    public function getLots() {
        if(empty($_POST) || !isset($_POST['mouza_pargona_code']) || $_POST['mouza_pargona_code'] == '' || !isset($_POST['subdiv_cir_code']) || $_POST['subdiv_cir_code'] == '') {
            echo json_encode([
                'status'=>'FAILED',
                'responseType'=>1,
                'msg'=>'Input Parameter not set'
            ]);
            exit();
        }
        $sessionData = $this->session->all_userdata();
        if(!$sessionData) {
            echo json_encode([
                'status'=>'FAILED',
                'responseType'=>1,
                'msg'=>'Session is destroyed. Please Login Again'
            ]);
            exit();
        }
        $dist_code = $this->session->userdata('dist_code');
        $subdiv_cir_code = explode('_', $this->input->post('subdiv_cir_code'));
        if(count($subdiv_cir_code) < 2 || count($subdiv_cir_code) >2) {
            echo json_encode([
                'status'=>'FAILED',
                'responseType'=>1,
                'msg'=>'Error in Input Parameter'
            ]);
            exit();
        }
        $subdiv_code = $subdiv_cir_code[0];
        $cir_code = $subdiv_cir_code[1];
        $mouza_pargona_code = $this->input->post('mouza_pargona_code');

        $this->dataswitch();

        $lots = $this->Chithamodel->lotdetails($dist_code, $subdiv_code, $cir_code, $mouza_pargona_code);

        echo json_encode([
            'status'=>'SUCCESS',
            'responseType'=>2,
            'msg'=>'',
            'data'=>$lots
        ]);
        exit();

    }

    public function getVill() {

        if(empty($_POST) || !isset($_POST['mouza_pargona_code']) || $_POST['mouza_pargona_code'] == '' || !isset($_POST['cir_code']) || $_POST['cir_code'] == '' || !isset($_POST['lot_no']) || $_POST['lot_no'] == '') {
            echo json_encode([
                'status'=>'FAILED',
                'responseType'=>1,
                'msg'=>'Input Parameter not set'
            ]);
            exit();
        }

        $sessionData = $this->session->all_userdata();
        if(!$sessionData) {
            echo json_encode([
                'status'=>'FAILED',
                'responseType'=>1,
                'msg'=>'Session is destroyed. Please Login Again'
            ]);
            exit();
        }
       
        $dist_code = $this->session->userdata('dist_code');
        $subdiv_cir_code = $this->input->post('cir_code');
        $cir_code_arr = explode('_', $subdiv_cir_code);
        if(count($cir_code_arr) < 2 || count($cir_code_arr) >2) {
            echo json_encode([
                'status'=>'FAILED',
                'responseType'=>1,
                'msg'=>'Error in Input Parameter'
            ]);
            exit();
        }
        $subdiv_code = $cir_code_arr[0];
        $cir_code = $cir_code_arr[1];
        $mouza_pargona_code = $this->input->post('mouza_pargona_code');
        $lot_no = $this->input->post('lot_no');

        $this->dataswitch();

        if($dist_code == '21') {
            $villages = $this->db->query("select distinct l.mouza_pargona_code, l.lot_no, l.vill_townprt_code,l.loc_name from verified_dags vd join location l on vd.dist_code=l.dist_code and vd.subdiv_code = l.subdiv_code AND vd.cir_code = l.cir_code AND vd.mouza_pargona_code = l.mouza_pargona_code AND vd.lot_no = l.lot_no AND vd.vill_townprt_code= l.vill_townprt_code
            where vd.dist_code='$dist_code' and vd.subdiv_code='$subdiv_code' and vd.cir_code='$cir_code'and vd.mouza_pargona_code='$mouza_pargona_code' and vd.lot_no='$lot_no' and vd.vill_townprt_code!='00000' AND l.status='L' AND (vd.signed_by_lm != '' AND vd.signed_by_lm IS NOT NULL) AND (vd.signed_by_co != '' AND vd.signed_by_co IS NOT NULL) AND (signed_by_adc IS NULL OR signed_by_adc = '');")->result_array();
        }
        else{
            $villages = $this->db->query("select distinct l.mouza_pargona_code, l.lot_no, l.vill_townprt_code,l.loc_name from verified_dags vd join location l on vd.dist_code=l.dist_code and vd.subdiv_code = l.subdiv_code AND vd.cir_code = l.cir_code AND vd.mouza_pargona_code = l.mouza_pargona_code AND vd.lot_no = l.lot_no AND vd.vill_townprt_code= l.vill_townprt_code
            where vd.dist_code='$dist_code' and vd.subdiv_code='$subdiv_code' and vd.cir_code='$cir_code'and vd.mouza_pargona_code='$mouza_pargona_code' and vd.lot_no='$lot_no' and vd.vill_townprt_code!='00000' AND (vd.signed_by_lm != '' AND vd.signed_by_lm IS NOT NULL) AND (vd.signed_by_co != '' AND vd.signed_by_co IS NOT NULL) AND (signed_by_adc IS NULL OR signed_by_adc = '');")->result_array();
        }
        

        $villages = $this->isCOCompletedOfItsDags($dist_code, $subdiv_code, $cir_code, $villages);

        echo json_encode([
            'status'=>'SUCCESS',
            'responseType'=>2,
            'msg'=>'',
            'data'=>$villages
        ]);
        exit();
    }


    public function getVillages(){
        $this->dataswitch();
        $dist_code = $this->session->userdata('dist_code');
        $subdiv_cir_code = $this->input->post('cir_code');
        $cir_code_arr = explode('_', $subdiv_cir_code);
        $subdiv_code = $cir_code_arr[0];
        $cir_code = $cir_code_arr[1];

        $villages = $this->db->query("select distinct l.mouza_pargona_code, l.lot_no, l.vill_townprt_code,l.loc_name from verified_dags vd join location l on vd.dist_code=l.dist_code and vd.subdiv_code = l.subdiv_code AND vd.cir_code = l.cir_code AND vd.mouza_pargona_code = l.mouza_pargona_code AND vd.lot_no = l.lot_no AND vd.vill_townprt_code= l.vill_townprt_code
        where vd.dist_code='$dist_code' and vd.subdiv_code!='00' and vd.cir_code='$cir_code'and vd.mouza_pargona_code!='00' and vd.lot_no!='00' and vd.vill_townprt_code!='00000' AND (vd.signed_by_lm != '' OR vd.signed_by_lm IS NOT NULL) AND (vd.signed_by_co != '' OR vd.signed_by_co IS NOT NULL) AND (signed_by_adc IS NULL OR signed_by_adc = '');")->result_array();

        $villages = $this->isCOCompletedOfItsDags($dist_code, $subdiv_code, $cir_code, $villages);

        $resp_arr = ['success' => true, 'villages' => $villages, 'message' => 'Village fetched successfully'];

        echo json_encode($resp_arr);
        return;
    }

    private function isCOCompletedOfItsDags($dist_code, $subdiv_code, $cir_code, $villages){
        // Here those villages will come in which LM perform e-sign. Now We have to filter each village in which 100% dags have signed by LM or not
        $filtered_villages = [];
        $user_code = $this->session->userdata('user_code');
        $user = $this->db->where('user_code', $user_code)->get('users')->row();
        
        if(count($villages)){
            foreach($villages as $village){
                $conditions = [
                                'dist_code' => $dist_code,
                                'subdiv_code' => $subdiv_code,
                                'cir_code' => $cir_code,
                                'mouza_pargona_code' => $village['mouza_pargona_code'],
                                'lot_no' => $village['lot_no'],
                                'vill_townprt_code' => $village['vill_townprt_code'],
                            ];
                
                $co_dag_count = $this->db->where($conditions)
                                                ->where('user_desig_code', 'CO')
                                                ->get('alloted_dags')
                                                ->num_rows();

                $is_signed_count = $this->db->where($conditions)
                                                ->where('user_desig_code', 'CO')
                                                ->where('is_signed', 1)
                                                ->get('alloted_dags')
                                                ->num_rows();

                if($co_dag_count > 0 && ($co_dag_count == $is_signed_count)){
                    $limit = round($co_dag_count * ADC_E_SIGN_RANDOMIZE_PERCENTAGE / 100);
                    if($limit > 0){
                        $alloted_dag = $this->db->where($conditions)
                                                ->where([
                                                        'alloted_to' => $user_code,
                                                        'user_desig_code' => $user->user_desig_code
                                                    ])
                                                ->get('alloted_dags')->row();
                                                
                        if(!$alloted_dag){
                            array_push($filtered_villages, $village);
                            $alloted_dags = $this->db->where($conditions)
                                                    ->order_by('id', 'RANDOM')
                                                    ->where('user_desig_code', 'CO')
                                                    ->limit($limit)
                                                    ->get('alloted_dags')
                                                    ->result_array();
                            
                            foreach($alloted_dags as $alloted_dag){
                                $data = [
                                    'verified_dags_id' => $alloted_dag['verified_dags_id'],
                                    'dist_code' => $alloted_dag['dist_code'],
                                    'subdiv_code' => $alloted_dag['subdiv_code'],
                                    'cir_code' => $alloted_dag['cir_code'],
                                    'mouza_pargona_code' => $alloted_dag['mouza_pargona_code'],
                                    'lot_no' => $alloted_dag['lot_no'],
                                    'vill_townprt_code' => $alloted_dag['vill_townprt_code'],
                                    'dag_no' => $alloted_dag['dag_no'],
                                    'uuid' => $alloted_dag['uuid'],
                                    'alloted_to' => $user_code,
                                    'user_desig_code' => $user->user_desig_code,
                                    'username' => $user->username,
                                    'alloted_at' => date('Y-m-d H:i:s'),
                                    'is_signed' => 0,
                                ];
                                $this->db->insert('alloted_dags', $data);
                            }
                        }else{
                            $has_dag_left = $this->db->where($conditions)
                                                ->where([
                                                        'alloted_to' => $user_code,
                                                        'user_desig_code' => $user->user_desig_code,
                                                        'is_signed' => 0
                                                    ])
                                                ->get('alloted_dags')->row();
                            if($has_dag_left){
                                array_push($filtered_villages, $village);
                            }
                        }
                    }
                }
            }
        }
        
        return $filtered_villages;
    }

    public function getDags()
    {
        $this->dataswitch();
        $this->db->trans_begin();
        $dist_code = $this->session->userdata('dist_code');
        // $subdiv_code = $this->session->userdata('subdiv_code');
        // $mouza_code = $this->session->userdata('mouza_pargona_code');
        // $lot_no = $this->session->userdata('lot_no');
        $subdiv_cir_code = $this->input->post('cir_code');
        $mouza_lot_village = $this->input->post('vill_townprt_code');

        $cir_code_arr = explode('_', $subdiv_cir_code);
        $subdiv_code = $cir_code_arr[0];
        $cir_code = $cir_code_arr[1];
        if(empty($mouza_lot_village) || empty($subdiv_cir_code)){
            echo json_encode(['data' => []]);
            exit;
        } 
        $location_parts = explode('_', $mouza_lot_village);
        $mouza_pargona_code = $location_parts[0];
        $lot_no = $location_parts[1];
        $village = $location_parts[2];

        if(empty($cir_code) && empty($village)){
            echo json_encode(['data' => []]);
            return;
        }

        $verified_dags = $this->getVerifiedDagsDetails($dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no, $village);
        
        // For development purposes start
        if(DEVELOPMENT_MODE_STATUS == '1'){
            ini_set('memory_limit', '-1');
            ini_set('execution_limit', '-1');
            $this->generateAllADCSign($dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no, $village);
        }
        // For development purposes end

        $lms_all = [];
        if(count($verified_dags)){
            foreach($verified_dags as $recordMain){
                // Fetch details from chitha_basic based on verified DAGs
                $query = $this->makeQuery($dist_code, $recordMain['subdiv_code'], $cir_code, $recordMain['mouza_pargona_code'], $recordMain['lot_no'], $village, $recordMain['dag_no']);
                $records = $query->result();
                foreach ($records as $record) {
                    $lm_s = [];
                    $lm_s['dag_no'] = $record->dag_no;
                    $lm_s['patta_no'] = $record->patta_no;
                    $lm_s['dag_area'] = $record->bigha . '-' . $record->katha . '-' . $record->chatak . '-' . $record->ganda;
                    $lm_s['patta_type_code'] = $record->patta_type_code;
                    $lm_s['patta_type'] = $record->patta_type;
                    $lm_s['land_class'] = $record->land_type;
                    $actionLink = base_url('index.php/verification/ADCController/viewDetails?' .
                        'dist=' . $dist_code .
                        '&subdiv=' . $recordMain['subdiv_code'] .
                        '&cir=' . $cir_code .
                        '&mouza=' . $recordMain['mouza_pargona_code'] .
                        '&lot=' . $recordMain['lot_no'] .
                        '&vill=' . $village .
                        '&dag=' . $record->dag_no .
                        '&patta=' . $record->patta_no .
                        '&type=' . $record->patta_type_code);
                    $lm_s['action'] = "<a href='$actionLink'><button type='button' class='btn btn-info btn-sm'>View & Verify</button></a>";
                    $lms_all[] = $lm_s;
                }
            }
        }

        if($this->db->trans_status() == FALSE) {
            $this->db->trans_rollback();
        }
        else{
            $this->db->trans_commit();
        }
        
        echo json_encode(['data' => $lms_all]);
    }

    private function getVerifiedDagsDetails($dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no, $village)
    {
        $user_code = $this->session->userdata('user_code');
        $query = $this->db->query("
                                    SELECT distinct dist_code, subdiv_code, cir_code, mouza_pargona_code, lot_no, dag_no 
                                    FROM alloted_dags 
                                    WHERE dist_code = '$dist_code' 
                                        AND subdiv_code = '$subdiv_code' 
                                        AND cir_code = '$cir_code'
                                        AND mouza_pargona_code = '$mouza_pargona_code'
                                        AND lot_no = '$lot_no'
                                        AND vill_townprt_code = '$village' 
                                        AND alloted_to = '$user_code'
                                        AND is_signed = 0
                                "); 
        // $query = $this->db->query("
        //     SELECT distinct dist_code, subdiv_code, cir_code, mouza_pargona_code, lot_no, dag_no
        //     FROM verified_dags
        //     WHERE dist_code = '$dist_code'
        //         AND subdiv_code != '00'
        //         AND cir_code = '$cir_code'
        //         AND mouza_pargona_code !='00'
        //         AND lot_no!='00'
        //         AND vill_townprt_code = '$village'
        //         AND (signed_by_lm IS NOT NULL OR signed_by_lm != '')
        //         AND date_of_sign_lm IS NOT NULL
        //         AND (signed_by_co is not null OR signed_by_co != '') 
        //         AND date_of_sign_co IS NOT NULL
        //         AND (signed_by_adc IS NULL OR signed_by_adc = '')
        // ");
        return $query->result_array();
    }

    private function generateAllADCSign($dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no, $village){
        $user_code = $this->session->userdata('user_code');
        $user_desig_code = $this->session->userdata('user_desig_code');
        $conditions = [
                        'dist_code' => $dist_code,
                        'subdiv_code' => $subdiv_code,
                        'cir_code' => $cir_code,
                        'mouza_pargona_code' => $mouza_pargona_code,
                        'lot_no' => $lot_no,
                        'vill_townprt_code' => $village,
                    ];

        $alloted_dags = $this->db->where($conditions)
                                    ->where('alloted_to', $user_code)
                                    ->where('user_desig_code', $user_desig_code)
                                    ->where('is_signed', 0)
                                    ->get('alloted_dags')
                                    ->result_array();
        
        if(count($alloted_dags) > 0){
            foreach($alloted_dags as $alloted_dag){
                $this->db->where('id', $alloted_dag['verified_dags_id'])
                        ->update('verified_dags', [
                                                    'signed_by_adc' => $user_code,
                                                    'date_of_sign_adc' => date('Y-m-d H:i:s')
                                                ]);
                
                $this->db->where('id', $alloted_dag['id'])
                            ->where('user_desig_code', $user_desig_code)
                            ->update('alloted_dags', [
                                                        'is_signed' => 1
                                                    ]);
            }
        }
    }
    
    private function makeQuery($dist_code, $subdiv_code, $cir_code, $mouza_code, $lot_no, $village, $dag_no)
    {
        $sql = "SELECT 
            cb.dag_no AS dag_no,
            cb.patta_no AS patta_no,
            cb.dag_area_b AS bigha,
            cb.dag_area_k AS katha,
            cb.dag_area_lc AS chatak,
            cb.dag_area_g AS ganda,
            cb.patta_type_code AS patta_type_code,
            t1.patta_type AS patta_type,
            t2.land_type AS land_type,
            cb.vill_townprt_code AS vill_townprt_code
        FROM chitha_basic cb 
        JOIN patta_code t1 ON cb.patta_type_code = t1.type_code
        JOIN landclass_code t2 ON cb.land_class_code = t2.class_code
        WHERE 
            cb.dist_code = '$dist_code' AND cb.subdiv_code = '$subdiv_code' AND cb.cir_code = '$cir_code' AND cb.mouza_pargona_code = '$mouza_code' AND cb.lot_no = '$lot_no' 
            AND cb.vill_townprt_code = '$village' AND cb.dag_no = '$dag_no'";


        $text = "ORDER BY dag_no ASC";
        $sql .= " " . $text;

        return $this->db->query($sql);
    }

    public function viewDetails()
    {
        $formData = array(
            'dist_code'   => $this->input->get('dist'),
            'subdiv_code' => $this->input->get('subdiv'),
            'cir_code'    => $this->input->get('cir'),
            'mouza_pargona_code' => $this->input->get('mouza'),
            'lot_no' => $this->input->get('lot'),
            'vill_townprt_code' => $this->input->get('vill'),
            'dag_no' => $this->input->get('dag'),
            'patta_no' => $this->input->get('patta'),
            'patta_type_code' => $this->input->get('type'),
        );

        $data['dist_code'] = $dist_code = $formData['dist_code'];
        $data['subdiv_code'] = $subdiv_code = $formData['subdiv_code'];
        $data['circle_code'] = $circle_code = $formData['cir_code'];
        $data['mouza_code'] = $mouza_code = $formData['mouza_pargona_code'];
        $data['lot_no'] = $lot_no = $formData['lot_no'];
        $data['vill_code'] = $vill_code = $formData['vill_townprt_code'];
        $data['dag_no'] = $dag_no = $formData['dag_no'];
        $data['patta_no'] = $patta_no = $formData['patta_no'];
        $data['patta_type_code'] =  $patta_type_code = $formData['patta_type_code'];

        $this->dataswitch();
        $sessionDist = $this->session->userdata('dist_code');
        $sessionSDiv = $this->session->userdata('subdiv_code');
        $sessionCir = $this->session->userdata('cir_code');


        if ($sessionDist != $dist_code) {
            $this->session->set_flashdata('message', "You are not allowed to access the page !!");
            redirect(base_url() . "index.php/verification/ADCController/index");
        }

        $checkIfDagAlreadyVerified = $this->db->query("SELECT * FROM verified_dags WHERE dist_code=? AND subdiv_code=? AND cir_code=? AND mouza_pargona_code=? AND lot_no=? AND vill_townprt_code=? AND dag_no=? AND (signed_by_lm IS NOT NULL OR signed_by_lm != '') AND (signed_by_sk IS NOT NULL OR signed_by_sk != '') AND (signed_by_co IS NOT NULL OR signed_by_co != '') AND (signed_by_adc IS NOT NULL OR signed_by_adc != '')", [$dist_code, $subdiv_code, $circle_code, $mouza_code, $lot_no, $vill_code, $dag_no])->row();

        if(!empty($checkIfDagAlreadyVerified)) {
            $this->session->set_flashdata('message', "Dag Already Verified !!");
            redirect(base_url() . "index.php/verification/ADCController/index");
            exit();
        }

        $checkIfRecordExistinChithaBasic = $this->Chithamodel->checkIfRecordExistinChithaBasic($formData);
        if ($checkIfRecordExistinChithaBasic) {
            $data['page_header'] = 'View Dag Details';
            $data['base'] = $this->config->item('base_url');
            $districtdata = $this->MisModel->getDistrictName($dist_code);
            $subdivdata = $this->MisModel->getSubDivName($dist_code, $subdiv_code);
            $circledata = $this->MisModel->getCircleName($dist_code, $subdiv_code, $circle_code);
            $mouzadata = $this->MisModel->getMouzaName($dist_code, $subdiv_code, $circle_code, $mouza_code);
            $lotdata = $this->MisModel->getLotName($dist_code, $subdiv_code, $circle_code, $mouza_code, $lot_no);
            $villagedata = $this->MisModel->getVillageName($dist_code, $subdiv_code, $circle_code, $mouza_code, $lot_no, $vill_code);

            $data['namedata'] = array_merge($districtdata, $subdivdata, $circledata, $mouzadata, $lotdata, $villagedata);

            $data['record'] = $this->db->query(
                "SELECT cb.dag_no, cb.patta_no, cb.dag_area_b, cb.dag_area_k, cb.dag_area_lc, cb.dag_area_g, cb.dag_area_are, cb.dag_revenue, cb.dag_local_tax, t1.patta_type, t2.land_type 
                                            FROM chitha_basic cb 
                                            JOIN patta_code t1 ON cb.patta_type_code = t1.type_code 
                                            JOIN landclass_code t2 ON cb.land_class_code = t2.class_code 
                                            WHERE cb.dist_code = ? 
                                            AND cb.subdiv_code = ? 
                                            AND cb.cir_code = ? 
                                            AND cb.mouza_pargona_code = ? 
                                            AND cb.lot_no = ? 
                                            AND cb.vill_townprt_code = ? 
                                            AND cb.dag_no = ?",
                [$dist_code, $subdiv_code, $circle_code, $mouza_code, $lot_no, $vill_code, $dag_no]
            )->result();

            $sql = "SELECT cp.pdar_id, cp.pdar_name, cp.pdar_father, cdp.dag_por_b,cdp.dag_por_k,cdp.dag_por_lc,cdp.dag_por_g,cdp.pdar_land_acre 
                FROM chitha_pattadar cp 
                JOIN chitha_dag_pattadar cdp ON cp.dist_code = cdp.dist_code 
                AND cp.subdiv_code = cdp.subdiv_code 
                AND cp.cir_code = cdp.cir_code 
                AND cp.mouza_pargona_code = cdp.mouza_pargona_code 
                AND cp.lot_no = cdp.lot_no 
                AND cp.vill_townprt_code = cdp.vill_townprt_code 
                AND cp.patta_no = cdp.patta_no 
                AND cp.patta_type_code = cdp.patta_type_code 
                AND cp.pdar_id = cdp.pdar_id 
                WHERE cp.dist_code = ? 
                AND cp.subdiv_code = ? 
                AND cp.cir_code = ? 
                AND cp.mouza_pargona_code = ? 
                AND cp.lot_no = ? 
                AND cp.vill_townprt_code = ? 
                AND cp.patta_no = ? 
                AND cp.patta_type_code = ? 
                AND cdp.dag_no = ? 
                ORDER BY cp.pdar_id ASC";

            $data['pattadars'] = $this->db->query($sql, [$dist_code, $subdiv_code, $circle_code, $mouza_code, $lot_no, $vill_code, $patta_no, $patta_type_code, $dag_no])->result();

            $data['tenants'] = $this->db->query(
                "SELECT ct.tenant_name, ct.tenants_father, ct.khatian_no,ct.tenant_id, tt.tenant_type 
                                             FROM chitha_tenant ct 
                                             JOIN tenant_type tt ON ct.type_of_tenant = tt.type_code 
                                             WHERE ct.dist_code = ? 
                                             AND ct.subdiv_code = ? 
                                             AND ct.cir_code = ? 
                                             AND ct.mouza_pargona_code = ? 
                                             AND ct.lot_no = ? 
                                             AND ct.vill_townprt_code = ? 
                                             AND ct.dag_no = ?",
                [$dist_code, $subdiv_code, $circle_code, $mouza_code, $lot_no, $vill_code, $dag_no]
            )->result();
            $data['relname'] = $this->Chithamodel->relation();
            $data['base'] = $this->config->item('base_url');
            $data['signURL'] = base_url('index.php/verification/ADCController/getBaseSFile');
            $data['addhaar_consent_content'] = self::AADHAAR_CONSENT_CONTENT;
            $data['aadhaar_consent_checkbox_text'] = self::AADHAAR_CONSENT_CHECKBOX_TEXT;
            // $data['verify_check_url'] = base_url('index.php/ADCController/isVerified/' . $dist_code .'/'. $subdiv_code . '/' . $circle_code . '/' . $mouza_code . '/' . $lot_no . '/' . $vill_code . '/' . $dag_no);
            $data['_view'] = 'verification/view_dag_details';
            $this->load->view('layout/layout', $data);
        } else {
            $this->session->set_flashdata('message', "Data Doesn't Exist for provided Data !!");
            redirect(base_url() . "index.php/verification/ADCController/index");
        }
    }

    // public function isVerified($dist_code, $subdiv_code, $cir_code, $mouza_code, $lot_no, $village, $dag_no){
    //     $query = "select * from verified_dags where dist_code=? and subdiv_code=? and cir_code=? and mouza_pargona_code=? and lot_no=? and vill_townprt_code=? and dag_no=? and (signed_by_lm IS NOT NULL or signed_by_lm != '') and (signed_by_co IS NOT NULL or signed_by_co != '') and (signed_by_adc IS NULL or signed_by_adc = '')";

    //     $verified_dag = $this->db->query($query, [$dist_code, $subdiv_code, $cir_code, $mouza_code, $lot_no, $village, $dag_no])->result();

    //     $response = [
    //         'success' => true,
    //         'is_verified' => $verified_dag ? true : false
    //     ];

    //     echo json_encode($response);

    //     return ;
        
    // }

    public function getBaseSFile()
    {
        $dist_code = $this->input->post("dist_code");
        $subdiv_code = $this->input->post("subdiv_code");
        $cir_code = $this->input->post("cir_code");
        $mouza_pargona_code = $this->input->post("mouza_pargona_code");
        $lot_no = $this->input->post("lot_no");
        $vill_townprt_code = $this->input->post("vill_townprt_code");
        $patta_no = $this->input->post("patta_no");
        $patta_type_code = $this->input->post("patta_type_code");
        $dag_no = $this->input->post("dag_no");

        $this->dataswitch();
        $this->db->trans_begin();

        $dag_no_int = $this->db->query("SELECT dag_no_int FROM chitha_basic WHERE dist_code=? AND subdiv_code=? AND cir_code=? AND mouza_pargona_code=? AND lot_no=? AND vill_townprt_code=? AND dag_no=?", [$dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no, $vill_townprt_code, $dag_no])->row()->dag_no_int;

        $sub_folder = $dist_code . '_' . $subdiv_code . '_' . $cir_code . '_' . $mouza_pargona_code . '_' . $lot_no . '_' . $vill_townprt_code;
        $file_name = $dist_code . '_' . $subdiv_code . '_' . $cir_code . '_' . $mouza_pargona_code . '_' . $lot_no . '_' . $vill_townprt_code . '_' . $dag_no_int;

        if(file_exists(BARAK_VALLEY_CHITHA_FRESH_PDF_DIR . $sub_folder . '/' . $file_name . '.pdf')) {
            $check = $this->db->query('SELECT * FROM verified_dags WHERE dist_code=? AND subdiv_code=? AND cir_code=? AND mouza_pargona_code=? AND lot_no=? AND vill_townprt_code=? AND dag_no=?', [$dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no, $vill_townprt_code, $dag_no])->row();

            if(empty($check) || $check->signed_by_lm == '' || $check->signed_by_sk == '' || $check->signed_by_co == '') {
                $this->db->trans_rollback();
                $response = [
                    'status'=>'FAILED',
                    'responseType'=>1,
                    'msg'=> 'Dag not verified'
                ];
        
                echo json_encode($response);
                exit();
            }

            // $lm_name = $this->db->query("SELECT lc.lm_name FROM loginuser_table lut  JOIN lm_code lc ON lc.dist_code = lut.dist_code 
            //                         AND lc.subdiv_code = lut.subdiv_code AND lc.cir_code = lut.cir_code AND lc.mouza_pargona_code = lut.mouza_pargona_code 
            //                         AND lc.lot_no = lut.lot_no AND lc.lm_code=lut.user_code WHERE lut.dis_enb_option = 'E' AND lc.dist_code=? AND lc.subdiv_code=? AND lc.cir_code=? 
            //                         AND lc.mouza_pargona_code=? AND lc.lot_no=?", [$dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no])->row();
            $lot_mondals = $this->db->query("SELECT lc.lm_name FROM loginuser_table lut  JOIN lm_code lc ON lc.dist_code = lut.dist_code 
                                    AND lc.subdiv_code = lut.subdiv_code AND lc.cir_code = lut.cir_code AND lc.mouza_pargona_code = lut.mouza_pargona_code 
                                    AND lc.lot_no = lut.lot_no AND lc.lm_code=lut.user_code WHERE lut.dis_enb_option = 'E' AND lc.dist_code=? AND lc.subdiv_code=? AND lc.cir_code=? 
                                    AND lc.mouza_pargona_code=? AND lc.lot_no=?", [$dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no])->result();

            // $lm_name = $lm_name ? $lm_name->lm_name : '';
            
            // log_message('error', 'LM LAST QUERY => ' . $this->db->last_query());
            // $lm_name = $this->db->query("SELECT lm_name FROM lm_code WHERE dist_code=? AND subdiv_code=? AND cir_code=? AND mouza_pargona_code=? AND lot_no=? AND lm_code=? AND status='E'", [$dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no, $check->signed_by_lm])->row()->lm_name;

            $sk_name = $this->db->query("SELECT username FROM users WHERE dist_code=? AND subdiv_code=? AND cir_code=? AND user_code=? AND user_desig_code='SK'", [$dist_code, $subdiv_code, $cir_code, $check->signed_by_sk])->row()->username;

            $co_name = $this->db->query("SELECT username FROM users WHERE dist_code=? AND subdiv_code=? AND cir_code=? AND user_code=? AND user_desig_code='CO'", [$dist_code, $subdiv_code, $cir_code, $check->signed_by_co])->row()->username;

            $existing_consent = json_decode($check->consents);
            $existing_consent = (array) $existing_consent;
            $existing_consent['ADC'] = [
                                        'consent_content' => self::AADHAAR_CONSENT_CONTENT,
                                        'consent_checkbox_text' => self::AADHAAR_CONSENT_CHECKBOX_TEXT,
                                    ];
            $updateData = [
                'consents' => json_encode($existing_consent)
            ];

            $this->db->where(['dist_code'=>$dist_code, 'subdiv_code'=>$subdiv_code, 'cir_code'=>$cir_code, 'mouza_pargona_code'=>$mouza_pargona_code, 'lot_no'=>$lot_no, 'vill_townprt_code'=>$vill_townprt_code, 'dag_no'=>$dag_no]);
            $status = $this->db->update('verified_dags', $updateData);
            if($status && $this->db->affected_rows() == 1){
                define('ESIGN_ROOT_DIRECTORY_CON', base_url() . 'esign/');
                // $user = $this->db->query("SELECT use_name FROM loginuser_table WHERE dist_code=? AND subdiv_code=? AND cir_code=? AND mouza_pargona_code=? AND lot_no=? AND user_code=?", [$dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no, $this->session->userdata('user_code')])->row();
                $user = $this->db->query("SELECT u.username, lut.use_name FROM loginuser_table lut join users u on u.dist_code=lut.dist_code AND u.user_code=lut.user_code WHERE lut.dist_code=? AND lut.user_code=?", [$dist_code, $this->session->userdata('user_code')])->row();

                if(count((array) $lot_mondals) > 0){
                    $lm_names = [];
                    foreach($lot_mondals as $lot_mondal){
                        $lm_name = $lot_mondal->lm_name;
                        if($lm_name != ''){
                            $translate = translateAssToEng($lm_name);
                            if(!$translate['success']){
                                $this->db->trans_rollback();
                                $response = [
                                    'status'=>'FAILED',
                                    'responseType'=>1,
                                    'msg'=> $translate['message']
                                ];
                                echo json_encode($response);
                                exit();
                            }else{
                                // $lm_name = $translate['message'];
                                array_push($lm_names, $translate['message']);
                            }
                        }
                    }
                    if(count($lm_names) > 0){
                        $lm_name = implode(', ', $lm_names);
                    }
                }else{
                    $lm_name = '';
                }

                $translate = translateAssToEng($sk_name);
                if(!$translate['success']){
                    $this->db->trans_rollback();
                    $response = [
                        'status'=>'FAILED',
                        'responseType'=>1,
                        'msg'=> $translate['message']
                    ];
                    echo json_encode($response);
                    exit();
                }else{
                    $sk_name = $translate['message'];
                }

                $translate = translateAssToEng($co_name);
                if(!$translate['success']){
                    $this->db->trans_rollback();
                    $response = [
                        'status'=>'FAILED',
                        'responseType'=>1,
                        'msg'=> $translate['message']
                    ];
                    echo json_encode($response);
                    exit();
                }else{
                    $co_name = $translate['message'];
                }

                $adc_name = $user->username;
                $translate = translateAssToEng($adc_name);
                if(!$translate['success']){
                    $this->db->trans_rollback();
                    $response = [
                        'status'=>'FAILED',
                        'responseType'=>1,
                        'msg'=> $translate['message']
                    ];
                    echo json_encode($response);
                    exit();
                }else{
                    $adc_name = $translate['message'];
                }
    
                $arr = [
                    'dist_code'=>$dist_code,
                    'subdiv_code'=>$subdiv_code,
                    'cir_code'=>$cir_code,
                    'mouza_pargona_code'=>$mouza_pargona_code,
                    'lot_no'=>$lot_no,
                    'vill_townprt_code'=>$vill_townprt_code,
                    'dag_no'=>$dag_no,
                    'dag_no_int'=>$dag_no_int,
                    'sign_users'=> [
                        'lm'=>[
                            'user_name' => $lm_name,
                            // 'date_of_sign' => date('Y-m-d', strtotime($check->date_of_sign_lm)),
                            // 'time_of_sign' => date('H:i:s', strtotime($check->date_of_sign_lm))
                        ],
                        'sk'=>[
                            'user_name' => $sk_name,
                            'date_of_sign' => date('Y-m-d', strtotime($check->date_of_sign_sk)),
                            'time_of_sign' => date('H:i:s', strtotime($check->date_of_sign_sk))
                        ],
                        'co'=>[
                            'user_name' => $co_name,
                            'date_of_sign' => date('Y-m-d', strtotime($check->date_of_sign_co)),
                            'time_of_sign' => date('H:i:s', strtotime($check->date_of_sign_co))
                        ],
                        'adc'=>[
                            'user_name' => $adc_name,
                            'date_of_sign' => date('Y-m-d'),
                            'time_of_sign' => date('H:i:s')
                        ]
                    ],
                    // 'user_name'=>$user->use_name,
                    'user_code'=> $this->session->userdata('user_code'),
                    'user_desig_code' => $this->session->userdata('user_desig_code')
                ];
                // $param = base64_encode(json_encode($arr));
                $param = urlencode(base64_encode(openssl_encrypt(json_encode($arr), "AES-128-CTR", "singleENCRYPT", 0, "1234567893032221")));

                if($this->db->trans_status() == FALSE) {
                    $this->db->trans_rollback();
                    $response = [
                        'status'=>'FAILED',
                        'responseType'=>1,
                        'msg'=> 'Chitha Pdf Generation Failed!'
                    ];
            
                    echo json_encode($response);
                    exit();
                }

                $this->db->trans_commit();

                $response = [
                    'status'=>'SUCCESS',
                    'responseType'=>0,
                    'msg'=> 'Chitha Pdf Generated Successfully!',
                    'data'=> [
                        'url'=>ESIGN_ROOT_DIRECTORY_CON . 'index.php?param=' . $param 
                    ]
                ];
    
                echo json_encode($response);
                exit();
            }
        }

        $this->db->trans_rollback();
        $response = [
            'status'=>'FAILED',
            'responseType'=>1,
            'msg'=> 'Chitha Pdf Generation Failed!'
        ];

        echo json_encode($response);
        exit();
    }

    public function viewSignedPdf() {
        $user_desig_code = $this->session->userdata('user_desig_code');
        $dist_code = $this->session->userdata('dcode');
        if($user_desig_code == 'CO' || $user_desig_code == 'SK' || $user_desig_code == 'LM') {
            $subdiv_code = $this->session->userdata('subdiv_code');
            $cir_code = $this->session->userdata('cir_code');
        }
        if($user_desig_code == 'LM') {
            $mouza_pargona_code = $this->session->userdata('mouza_pargona_code');
            $lot_no = $this->session->userdata('lot_no');
        }

        $this->dataswitch();

        if($user_desig_code == 'ADC' || $user_desig_code == 'DC') {
            $circles = $this->db->query("SELECT loc_name, locname_eng, dist_code, subdiv_code, cir_code FROM location WHERE dist_code=? AND subdiv_code!='00' AND cir_code!='00' AND mouza_pargona_code='00' AND lot_no='00' AND vill_townprt_code='00000'", [$dist_code])->result();
        }
        else{
            $circles = [];
        }

        if($user_desig_code == 'DC' || $user_desig_code == 'ADC') {
            if($dist_code == '21') {
                $villages = $this->db->query("SELECT loc_name, locname_eng, uuid, vill_townprt_code, cir_code, dist_code, subdiv_code FROM location WHERE dist_code=? AND subdiv_code=? AND cir_code=? AND mouza_pargona_code!='00' AND lot_no!='00' AND vill_townprt_code!='00000' AND status='L'", [$dist_code, '01', '03'])->result();
            }
            else {
                $villages = $this->db->query("SELECT loc_name, locname_eng, uuid, vill_townprt_code, cir_code, dist_code, subdiv_code FROM location WHERE dist_code=? AND subdiv_code=? AND cir_code=? AND mouza_pargona_code!='00' AND lot_no!='00' AND vill_townprt_code!='00000'", [$dist_code, '01', '03'])->result();
            }
        }
        else if($user_desig_code == 'CO' || $user_desig_code == 'SK') {
            if($dist_code == '21') {
                $villages = $this->db->query("SELECT loc_name, locname_eng, uuid, vill_townprt_code, cir_code, dist_code, subdiv_code FROM location WHERE dist_code=? AND subdiv_code=? AND cir_code=? AND mouza_pargona_code!='00' AND lot_no!='00' AND vill_townprt_code!='00000' AND status='L'", [$dist_code, $subdiv_code, $cir_code])->result();
            }
            else {
                $villages = $this->db->query("SELECT loc_name, locname_eng, uuid, vill_townprt_code, cir_code, dist_code, subdiv_code FROM location WHERE dist_code=? AND subdiv_code=? AND cir_code=? AND mouza_pargona_code!='00' AND lot_no!='00' AND vill_townprt_code!='00000'", [$dist_code, $subdiv_code, $cir_code])->result();
            }
        }
        else if($user_desig_code == 'LM') {
            if($dist_code == '21') {
                $villages = $this->db->query("SELECT loc_name, locname_eng, uuid, vill_townprt_code, cir_code, dist_code, subdiv_code FROM location WHERE dist_code=? AND subdiv_code=? AND cir_code=? AND mouza_pargona_code=? AND lot_no=? AND vill_townprt_code!='00000' AND status='L'", [$dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no])->result();
            }
            else {
                $villages = $this->db->query("SELECT loc_name, locname_eng, uuid, vill_townprt_code, cir_code, dist_code, subdiv_code FROM location WHERE dist_code=? AND subdiv_code=? AND cir_code=? AND mouza_pargona_code=? AND lot_no=? AND vill_townprt_code!='00000'", [$dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no])->result();
            }
        }

        if(!empty($villages)) {
            foreach($villages as $village) {
                $village->cir_name = $this->utilityclass->getCircleName($village->dist_code, $village->subdiv_code, $village->cir_code);
            }
        }

        if(isset($_POST['uuid']) && $_POST['uuid']!='') {
            $uuid = $this->input->post('uuid');
            $location_names = $this->db->query("SELECT dist_code, subdiv_code, cir_code, mouza_pargona_code, lot_no, vill_townprt_code FROM location WHERE uuid=?", [$uuid])->row();
        }
        else {
            $uuid = $villages[0]->uuid;
            $location_names = $this->db->query("SELECT dist_code, subdiv_code, cir_code, mouza_pargona_code, lot_no, vill_townprt_code FROM location WHERE uuid=?", [$uuid])->row();
        }

        $dist_name = $this->utilityclass->getDistrictName($location_names->dist_code);
        $subdiv_name = $this->utilityclass->getSubDivName($location_names->dist_code, $location_names->subdiv_code);
        $cir_name = $this->utilityclass->getCircleName($location_names->dist_code, $location_names->subdiv_code, $location_names->cir_code);
        $mouza_pargona_name = $this->utilityclass->getMouzaName($location_names->dist_code, $location_names->subdiv_code, $location_names->cir_code, $location_names->mouza_pargona_code);
        $lot_name = $this->utilityclass->getLotLocationName($location_names->dist_code, $location_names->subdiv_code, $location_names->cir_code, $location_names->mouza_pargona_code, $location_names->lot_no);
        $vill_townprt_name = $this->utilityclass->getVillageName($location_names->dist_code, $location_names->subdiv_code, $location_names->cir_code, $location_names->mouza_pargona_code, $location_names->lot_no, $location_names->vill_townprt_code);

        if($user_desig_code == 'DC') {
            $verifiedDags = $this->db->query("SELECT id, dag_no, date_of_sign_lm, date_of_sign_sk, date_of_sign_co, date_of_sign_adc, date_of_sign_dc, signed_doc, uuid FROM verified_dags WHERE uuid=? AND (signed_by_dc IS NOT NULL AND signed_by_dc != '') AND (signed_doc IS NOT NULL AND signed_doc != '')", [$uuid])->result();
        }
        else if($user_desig_code == 'ADC') {
            $verifiedDags = $this->db->query("SELECT id, dag_no, date_of_sign_lm, date_of_sign_sk, date_of_sign_co, date_of_sign_adc, date_of_sign_dc, signed_doc, uuid FROM verified_dags WHERE uuid=? AND (signed_by_adc IS NOT NULL AND signed_by_adc != '') AND (signed_doc IS NOT NULL AND signed_doc != '')", [$uuid])->result();
        }
        else if ($user_desig_code == 'CO') {
            $verifiedDags = $this->db->query("SELECT id, dag_no, date_of_sign_lm, date_of_sign_sk, date_of_sign_co, date_of_sign_adc, date_of_sign_dc, signed_doc, uuid FROM verified_dags WHERE uuid=? AND (signed_by_co IS NOT NULL AND signed_by_co != '') AND (signed_doc IS NOT NULL AND signed_doc != '')", [$uuid])->result();
        }
        else if($user_desig_code == 'SK') {
            $verifiedDags = $this->db->query("SELECT id, dag_no, date_of_sign_lm, date_of_sign_sk, date_of_sign_co, date_of_sign_adc, date_of_sign_dc, signed_doc, uuid FROM verified_dags WHERE uuid=? AND (signed_by_sk IS NOT NULL AND signed_by_sk != '') AND (signed_doc IS NOT NULL AND signed_doc != '')", [$uuid])->result();
        }
        else if($user_desig_code == 'LM') {
            $verifiedDags = $this->db->query("SELECT id, dag_no, date_of_sign_lm, date_of_sign_sk, date_of_sign_co, date_of_sign_adc, date_of_sign_dc, signed_doc, uuid FROM verified_dags WHERE uuid=? AND (signed_by_lm IS NOT NULL AND signed_by_lm != '') AND (signed_doc IS NOT NULL AND signed_doc != '')", [$uuid])->result();
        }

        $verified_dags = [];

        foreach($verifiedDags as $verifiedDag) {
            if(file_exists(BARAK_VALLEY_CHITHA_PDF_DIR . $verifiedDag->signed_doc)) {
                $file_name_array = explode('/', $verifiedDag->signed_doc);
                $file_name = $file_name_array[count($file_name_array)-1];
                $verifiedDag->param = $verifiedDag->uuid . '_' . $file_name;
                if($user_desig_code == 'LM') {
                    $verifiedDag->sign_date = date('d-m-Y H:i:s', strtotime($verifiedDag->date_of_sign_lm));
                }
                else if($user_desig_code == 'SK') {
                    $verifiedDag->sign_date = date('d-m-Y H:i:s', strtotime($verifiedDag->date_of_sign_sk));
                }
                else if($user_desig_code == 'CO') {
                    $verifiedDag->sign_date = date('d-m-Y H:i:s', strtotime($verifiedDag->date_of_sign_co));
                }
                else if($user_desig_code == 'ADC') {
                    $verifiedDag->sign_date = date('d-m-Y H:i:s', strtotime($verifiedDag->date_of_sign_adc));
                }
                else if($user_desig_code == 'DC') {
                    $verifiedDag->sign_date = date('d-m-Y H:i:s', strtotime($verifiedDag->date_of_sign_dc));
                }
                $verified_dags[] = $verifiedDag;
            }
        }

        $data['circles'] = $circles;
        $data['villages'] = $villages;
        $data['location_names'] = 'District: ' . $dist_name . ', Sub-Divisional: ' . $subdiv_name . ', Circle: ' . $cir_name . ', Mouza: ' . $mouza_pargona_name . ', Lot: ' . $lot_name . ', Village: ' . $vill_townprt_name;
        $data['verified_dags'] = $verified_dags;

        if(isset($_POST['uuid']) && $_POST['uuid']!='') {
            echo json_encode([
                'status'=>'SUCCESS',
                'responseType'=>2,
                'data'=>$data
            ]);
            exit();
        }
        else{
            $data['_view'] = 'verification/adc/view_signed_doc';
            $this->load->view('layout/layout', $data);
        }
    }

    public function villages() {
        $loc_code = $this->input->post('cir_code');
        $loc_code_array = explode('-', $loc_code);

        $dist_code = $loc_code_array[0];
        $subdiv_code = $loc_code_array[1];
        $cir_code = $loc_code_array[2];

        $this->dataswitch();

        if($dist_code == '21') {
            $villages = $this->db->query("SELECT loc_name, locname_eng, uuid FROM location WHERE dist_code=? AND subdiv_code=? AND cir_code=? AND mouza_pargona_code!='00' AND lot_no!='00' AND vill_townprt_code!='00000' AND status='L'", [$dist_code, $subdiv_code, $cir_code])->result();
        }
        else {
            $villages = $this->db->query("SELECT loc_name, locname_eng, uuid FROM location WHERE dist_code=? AND subdiv_code=? AND cir_code=? AND mouza_pargona_code!='00' AND lot_no!='00' AND vill_townprt_code!='00000'", [$dist_code, $subdiv_code, $cir_code])->result();
        }

        echo json_encode($villages);
    }

    public function getSignedPdf() {
        $param = $this->input->get('param');
        $file_name_array = explode('_', $param);
        $uuid = $file_name_array[0];
        unset($file_name_array[0]);
        $file_name = implode('_', $file_name_array);
        
        $this->dataswitch();
        $location = $this->db->query("SELECT * FROM location WHERE uuid=?", [$uuid])->row();
        $folder = $location->dist_code . '_' . $location->subdiv_code . '_' . $location->cir_code . '_' . $location->mouza_pargona_code . '_' . $location->lot_no . '_' . $location->vill_townprt_code;

        if(file_exists(BARAK_VALLEY_CHITHA_PDF_DIR . $folder . '/' . $file_name)) {
            $file_path = BARAK_VALLEY_CHITHA_PDF_DIR . $folder . '/' . $file_name;
            $content_type = 'application/pdf';

            header('Content-Type: ' . $content_type);
            header('Content-Length: ' . filesize($file_path));
            ob_clean();
            echo file_get_contents($file_path);
        }
    }
    public function verificationCertificate() {
        $this->dataswitch();

        $dist_code = $this->session->userdata('dcode');

        $data = $this->getVerificationCertificateData();
        $validationStatus = $this->VerificationModel->isCertificateReadyToEsign($data['villages']);
        $data['validationStatus'] = $validationStatus;

        $chitha_verification_certificate = $this->db->where('dist_code', $dist_code)
                                                ->where('subdiv_code', '00')
                                                ->where('cir_code', '00')
                                                ->where('mouza_pargona_code', '00')
                                                ->where('lot_no', '00')
                                                ->where('user_desig_code', 'ADC')
                                                ->get('chitha_verification_certificates')
                                                ->row();
        
        $data['chitha_verification_certificate'] = null;
        
        if($chitha_verification_certificate){
            if(!$chitha_verification_certificate->signed_by || !$chitha_verification_certificate->signed_file_name){
                $this->db->where('id', $chitha_verification_certificate->id)->delete('chitha_verification_certificates');
                unlink(VERIFICATION_CERTICATE_ESIGN_PATH . $chitha_verification_certificate->file_name);
            }else{
                $data['chitha_verification_certificate'] = $chitha_verification_certificate;
            }
        }
        
        $data['addhaar_consent_content'] = self::AADHAAR_CONSENT_CONTENT;
        $data['aadhaar_consent_checkbox_text'] = self::AADHAAR_CONSENT_CHECKBOX_TEXT;

        $data['_view'] = 'verification/adc/certificate';

        $this->load->view('layout/layout', $data);
    }

    
    public function eSignInit(){
        $dist_code = $this->session->userdata('dcode');
        $subdiv_code = $this->session->userdata('subdiv_code');
        $cir_code = $this->session->userdata('cir_code');
        $mouza_pargona_code = $this->session->userdata('mouza_pargona_code');
        $lot_no = '00';

        $this->dataswitch();

        $user = $this->db->query("SELECT u.username, lut.use_name FROM loginuser_table lut join users u on u.dist_code=lut.dist_code and u.subdiv_code=lut.subdiv_code and u.cir_code=lut.cir_code and u.user_code=lut.user_code WHERE lut.dist_code=? AND lut.subdiv_code=? AND lut.cir_code=? AND lut.user_code=?", [$dist_code, $subdiv_code, $cir_code, $this->session->userdata('user_code')])->row();

        $adc_name = '';
        $translate = translateAssToEng($user->username);
        if(!$translate['success']){
            $response = [
                'status'=>'FAILED',
                'responseType'=>1,
                'msg'=> $translate['message']
            ];
            echo json_encode($response);
            exit();
        }else{
            $adc_name = $translate['message'];
        }

        
        $check_chitha_verification_certificate = $this->db->where('dist_code', $dist_code)
                                                    ->where('subdiv_code', $subdiv_code)
                                                    ->where('cir_code', $cir_code)
                                                    ->where('mouza_pargona_code', $mouza_pargona_code)
                                                    ->where('lot_no', '00')
                                                    ->where('user_desig_code', 'ADC')
                                                    ->get('chitha_verification_certificates')
                                                    ->row();
        
        if($check_chitha_verification_certificate){
            if($check_chitha_verification_certificate->signed_file_name){
                $response = [
                    'status' => 'FAILED',
                    'responseType' => 1,
                    'msg' => 'Certificate has already been signed'
                ];
        
                echo json_encode($response);
                return;
            }

            $file_name = $check_chitha_verification_certificate->file_name;
        }else{
            if ((!file_exists(VERIFICATION_CERTICATE_ESIGN_PATH) == true)) {
                mkdir(VERIFICATION_CERTICATE_ESIGN_PATH, 0777, true);
            }
            
            $this->db->trans_begin();

            $file_name = $dist_code . '_' . $subdiv_code . '_' . $cir_code . '_' .$mouza_pargona_code . '_ADC_' . uniqid() . '.pdf';
    
            $data = $this->getVerificationCertificateData();
            $validationStatus = $this->VerificationModel->isCertificateReadyToEsign($data['villages']);
            if(!$validationStatus['success']){
                $response = [
                    'status' => 'FAILED',
                    'responseType' => 1,
                    'msg' => $validationStatus['message']
                ];
                echo json_encode($response);
                exit();
            }
    
            $this->load->helper('language');
    
            $html = $this->load->view('verification/adc/certificate-partials', $data, TRUE);
            
            ini_set("pcre.backtrack_limit", "500000000");
            ini_set('max_execution_time', '0');
            include 'vendor/mpdf/vendor/autoload.php';
    
            $mpdf = new \Mpdf\Mpdf([
                'default_font_size' => 11,
                'default_font' => 'dejavusans',
                'orientation' => 'P',
                'format' => 'A4',
            ]);
    
            $mpdf->autoScriptToLang = true;
            $mpdf->autoLangToFont = true;
            $mpdf->shrink_tables_to_fit = 1;
            $mpdf->use_kwt = true;
    
            $mpdf->WriteHTML($html);
    
            // Or save to a file
            $mpdf->Output(VERIFICATION_CERTICATE_ESIGN_PATH . $file_name, \Mpdf\Output\Destination::FILE);
            
            $consentsArr = [
                                'consent_content' => self::AADHAAR_CONSENT_CONTENT,
                                'consent_checkbox_text' => self::AADHAAR_CONSENT_CHECKBOX_TEXT,
                            ];
    
            $data = [
                'dist_code' => $dist_code,
                'subdiv_code' => $subdiv_code,
                'cir_code' => $cir_code,
                'mouza_pargona_code' => $mouza_pargona_code,
                'lot_no' => $lot_no,
                'user_desig_code' => 'ADC',
                'file_name' => $file_name,
                'consents' => json_encode($consentsArr),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ];
            // chitha_verification_certificates
            $status = $this->db->insert('chitha_verification_certificates', $data);
            if($status){
                $this->db->trans_commit();
            }else{
                $this->db->trans_rollback();
                log_message('error', '#ERRVERCERT0004: Last Query => ' . $this->db->last_query());
                $response = [
                    'status' => 'FAILED',
                    'responseType' => 1,
                    'msg' => '#ERRVERCERT0004: Something went wrong. Please try again later.'
                ];
                echo json_encode($response);
                exit();
            }
            
        }
        
        define('ESIGN_ROOT_DIRECTORY_CON', base_url() . 'esign/');
        
        // $user = $this->db->query("SELECT u.username, lut.use_name FROM loginuser_table lut join users u on u.dist_code=lut.dist_code and u.subdiv_code=lut.subdiv_code and u.cir_code=lut.cir_code and u.user_code=lut.user_code WHERE lut.dist_code=? AND lut.subdiv_code=? AND lut.cir_code=? AND lut.user_code=?", [$dist_code, $subdiv_code, $cir_code, $this->session->userdata('user_code')])->row();

        $arr = [
            'dist_code' => $dist_code,
            'subdiv_code' => $subdiv_code,
            'cir_code' => $cir_code,
            'mouza_pargona_code' => $mouza_pargona_code,
            'lot_no' => '00',
            'sign_users' => [
                'adc' => [
                    'user_name' => $adc_name,
                    'date_of_sign' => date('Y-m-d'),
                    'time_of_sign' => date('H:i:s')
                ]
            ],
            'file_name' => $file_name,
            'user_code' => $this->session->userdata('user_code'),
            'user_desig_code' => $this->session->userdata('user_desig_code'),
            'redirect' => 'verification/ADCController/verificationCertificate',
            'is_final' => '0'
        ];
        $param = urlencode(base64_encode(openssl_encrypt(json_encode($arr), "AES-128-CTR", "singleENCRYPT", 0, "1234567893032221")));

        $response = [
            'status' => 'SUCCESS',
            'responseType' => 0,
            'msg' => 'Verification certificate is ready to sign',
            'data' => [
                'url' => ESIGN_ROOT_DIRECTORY_CON . 'verify_chitha_certificate/index.php?param=' . $param
                // 'dist_code'=>$dist_code,
                // 'subdiv_code'=>$subdiv_code,
                // 'cir_code'=>$cir_code,
                // 'mouza_pargona_code'=>$mouza_pargona_code,
                // 'lot_no'=>$lot_no,
                // 'vill_townprt_code'=>$vill_townprt_code,
            ]
        ];
        echo json_encode($response);
        exit();
        
    }

    protected function getVerificationCertificateData(){
        $this->load->model('verification/VerificationModel');

        $dist_code = $this->session->userdata('dcode');

        $district = $this->db->query("SELECT loc_name, locname_eng FROM location WHERE dist_code=? AND subdiv_code=?", [$dist_code,'00'])->row();
        $dist_name = $district->loc_name . ' (' . $district->locname_eng . ')';
        $data['dist_name'] = $dist_name;

        $user_code = $this->session->userdata('usercode');
        $data['adc_name'] = $this->db->query("SELECT username FROM users WHERE dist_code=? AND user_code=?",[$dist_code,$user_code])->row()->username;

        $villages = $this->VerificationModel->getVillages();

        $data['villages'] = $villages;

        return $data;
    }
}
