<?php
defined('BASEPATH') or exit('No direct script access allowed');
include APPPATH . '/libraries/CommonTrait.php';

class LMController extends CI_Controller
{
    use CommonTrait;

    const AADHAAR_CONSENT_CONTENT = ' <p>I hereby give my consent for using my identity and address data received from e-KYC provider to generate and submit the electronic DSC application form to CA, creation of key pairs by ESP on my behalf, submission of certificate to CA for certification, one time creation of signature on the hash along with this request, deletion of key pairs after applyingsignature(s). I have noobjection in the use of my ID for authenticating myself with Aadhaar based authentication system for the purposes of availing of the eCabinet from Home & Political Department, Government of Assam. I understand that the Biometrics and/or OTP I provide for authentication shall be used only for authenticating my identity through the Aadhaar Authentication system, for obtaining my e-KYC through Aadhaar e-KYC service and for the issuance of Digital Signature Certificate (DSC) for this specific transaction and for no other purposes.For the creation of DSC, I understand that the options that I have chosen are the ones that shall be populated in the DSC generated by the CA and I provide my consent for the same. I also understand that the following fields in the DSC generated by the CA are mandatory and I give my consent for using the Aadhaar provided e-KYC information to populate the corresponding fields in the DSC.</p><p>Common Name (name as obtained from e-KYC), Unique Identifier (UID Token), Pseudonym (unique code sent by UIDAI in e-KYC response), State or Province (state as obtained from e-KYC), Postal Code (postal code as obtained from e-KYC)</p>';

    const AADHAAR_CONSENT_CHECKBOX_TEXT = 'I understand that Home & Political Department, Government of Assam shall ensure security and confidentiality of my personal identity data provided for the purpose of Aadhaar based authentication.';

    function __construct()
    {
        parent::__construct();
        $this->load->model('UserModel');
        $this->load->model('Chithamodel');
        $this->load->model('MisModel');
        $this->load->model('LoginModel');
        $this->load->model('chitha/DharChithaModel');

        $this->load->helper(array('form', 'url'));
        $this->load->library('form_validation');
        $this->load->helper('security');

        $this->load->helper('language');
        $district_code = $this->session->userdata('dist_code');
        if (in_array($district_code, BARAK_VALLEY)) {
            $this->lang->load("bengali", "bengali");
        } else {
            $this->lang->load("assamese", "assamese");
        }
    }
    public function index()
    {
        $this->dataswitch();
        //dd($this->session->userdata());
        $dist_code = $this->session->userdata('dist_code');
        $subdiv_code = $this->session->userdata('subdiv_code');
        $cir_code = $this->session->userdata('cir_code');
        $mouza_pargona_code = $this->session->userdata('mouza_pargona_code');
        $lot_no = $this->session->userdata('lot_no');
        $data['page_header'] = 'Chitha Verification';
        $data['villages'] = $this->Chithamodel->villagedetails($dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no);
        $data['ajax_url'] = base_url('index.php/verification/LMController/getDags');
        $data['_view'] = 'verification/lm/dashboard';
        $this->load->view('layout/layout', $data);
    }

    public function getDags()
    {
        $dist_code = $this->session->userdata('dist_code');
        $subdiv_code = $this->session->userdata('subdiv_code');
        $cir_code = $this->session->userdata('cir_code');
        $mouza_code = $this->session->userdata('mouza_pargona_code');
        $lot_no = $this->session->userdata('lot_no');
        $village = $this->input->post('vill_townprt_code');

        $this->dataswitch();
        $this->db->trans_begin();
        //dd($this->session->userdata);
        $query = $this->makeQuery($dist_code, $subdiv_code, $cir_code, $mouza_code, $lot_no, $village);

        $records = $query->result();
        $lms_all = [];
        foreach ($records as $record) {
            $lm_s = [];
            $lm_s['dag_no'] = $record->dag_no;
            $lm_s['patta_no'] = $record->patta_no;
            $lm_s['dag_area'] = $record->bigha . '-' . $record->katha . '-' . $record->chatak . '-' . $record->ganda;
            $lm_s['patta_type_code'] = $record->patta_type_code;
            $lm_s['patta_type'] = $record->patta_type;
            $lm_s['land_class'] = $record->land_type;
            // $actionLink = base_url('index.php/verification/LMVerificationController/viewDetails/' . $dist_code . '-' . $subdiv_code . '-' . $cir_code . '-' . $mouza_code . '-' . $lot_no . '-' . $village . '-' . $record->dag_no . '-' . $record->patta_no . '-' . $record->patta_type_code);

            $actionLink = base_url('index.php/verification/LMController/viewDetails?' .
                'dist=' . $dist_code .
                '&subdiv=' . $subdiv_code .
                '&cir=' . $cir_code .
                '&mouza=' . $mouza_code .
                '&lot=' . $lot_no .
                '&vill=' . $village .
                '&dag=' . $record->dag_no .
                '&patta=' . $record->patta_no .
                '&type=' . $record->patta_type_code);

            $lm_s['action'] = "<a href='$actionLink'><button type='button' class='btn btn-info btn-sm'>View & Verify</button></a>";

            $lms_all[] = $lm_s;
        }

        // For development purposes start
        if (DEVELOPMENT_MODE_STATUS == '1') {
            ini_set('memory_limit', '-1');
            ini_set('execution_limit', '-1');
            foreach ($lms_all as $lm_data) {
                $this->generateAllDagPdf($dist_code, $subdiv_code, $cir_code, $mouza_code, $lot_no, $village, $lm_data['patta_type_code'], $lm_data['dag_no']);
            }
        }
        // For development purposes end

        if($this->db->trans_status() == FALSE) {
            $this->db->trans_rollback();
        }
        else{
            $this->db->trans_commit();
        }

        echo json_encode(['data' => $lms_all]);
    }

    public function makeQuery($dist_code, $subdiv_code, $cir_code, $mouza_code, $lot_no, $village)
    {
        $sql = "SELECT 
            cb.dag_no AS dag_no,
            cb.patta_no AS patta_no,
            cb.dag_area_b AS bigha,
            cb.dag_area_k AS katha,
            cb.dag_area_lc AS chatak,
            cb.dag_area_g AS ganda,
            cb.patta_type_code AS patta_type_code,
            t1.patta_type AS patta_type,
            t2.land_type AS land_type
        FROM chitha_basic cb 
        JOIN patta_code t1 ON cb.patta_type_code = t1.type_code
        JOIN landclass_code t2 ON cb.land_class_code = t2.class_code
        LEFT JOIN verified_dags vd ON cb.dist_code = vd.dist_code 
            AND cb.subdiv_code = vd.subdiv_code 
            AND cb.cir_code = vd.cir_code 
            AND cb.mouza_pargona_code = vd.mouza_pargona_code 
            AND cb.lot_no = vd.lot_no 
            AND cb.vill_townprt_code = vd.vill_townprt_code 
            AND cb.dag_no = vd.dag_no
        WHERE 
            cb.dist_code = '$dist_code' 
            AND cb.subdiv_code = '$subdiv_code' 
            AND cb.cir_code = '$cir_code' 
            AND cb.mouza_pargona_code = '$mouza_code' 
            AND cb.lot_no = '$lot_no' 
            AND cb.vill_townprt_code = '$village'
            AND vd.dag_no IS NULL
        ORDER BY dag_no ASC";
        return $this->db->query($sql);
    }

    public function viewDetails()
    {
        $formData = array(
            'dist_code'   => $this->input->get('dist'),
            'subdiv_code' => $this->input->get('subdiv'),
            'cir_code'    => $this->input->get('cir'),
            'mouza_pargona_code' => $this->input->get('mouza'),
            'lot_no' => $this->input->get('lot'),
            'vill_townprt_code' => $this->input->get('vill'),
            'dag_no' => $this->input->get('dag'),
            'patta_no' => $this->input->get('patta'),
            'patta_type_code' => $this->input->get('type'),
        );

        $data['dist_code'] = $dist_code = $formData['dist_code'];
        $data['subdiv_code'] = $subdiv_code = $formData['subdiv_code'];
        $data['circle_code'] = $circle_code = $formData['cir_code'];
        $data['mouza_code'] = $mouza_code = $formData['mouza_pargona_code'];
        $data['lot_no'] = $lot_no = $formData['lot_no'];
        $data['vill_code'] = $vill_code = $formData['vill_townprt_code'];
        $data['dag_no'] = $dag_no = $formData['dag_no'];
        $data['patta_no'] = $patta_no = $formData['patta_no'];
        $data['patta_type_code'] =  $patta_type_code = $formData['patta_type_code'];

        $this->dataswitch();
        $sessionDist = $this->session->userdata('dist_code');
        $sessionSDiv = $this->session->userdata('subdiv_code');
        $sessionCir = $this->session->userdata('cir_code');
        $sessionMouza = $this->session->userdata('mouza_pargona_code');
        $sessionLot = $this->session->userdata('lot_no');


        if ($sessionDist != $dist_code || $sessionSDiv != $subdiv_code || $sessionCir != $circle_code || $sessionMouza != $mouza_code || $sessionLot != $lot_no) {
            $this->session->set_flashdata('message', "You are not allowed to access the page !!");
            redirect(base_url() . "index.php/verification/LMController/index");
        }

        $checkIfDagAlreadyVerified = $this->db->query("SELECT * FROM verified_dags WHERE dist_code=? AND subdiv_code=? AND cir_code=? AND mouza_pargona_code=? AND lot_no=? AND vill_townprt_code=? AND dag_no=? AND (signed_by_lm IS NOT NULL OR signed_by_lm != '') AND (token IS NOT NULL OR token != '')", [$dist_code, $subdiv_code, $circle_code, $mouza_code, $lot_no, $vill_code, $dag_no])->row();

        if (!empty($checkIfDagAlreadyVerified)) {
            $this->session->set_flashdata('message', "Dag Already Verified !!");
            redirect(base_url() . "index.php/verification/LMController/index");
            exit();
        }

        $checkIfRecordExistinChithaBasic = $this->Chithamodel->checkIfRecordExistinChithaBasic($formData);
        if ($checkIfRecordExistinChithaBasic) {
            $data['page_header'] = 'View Dag Details';
            $data['base'] = $this->config->item('base_url');
            $districtdata = $this->MisModel->getDistrictName($dist_code);
            $subdivdata = $this->MisModel->getSubDivName($dist_code, $subdiv_code);
            $circledata = $this->MisModel->getCircleName($dist_code, $subdiv_code, $circle_code);
            $mouzadata = $this->MisModel->getMouzaName($dist_code, $subdiv_code, $circle_code, $mouza_code);
            $lotdata = $this->MisModel->getLotName($dist_code, $subdiv_code, $circle_code, $mouza_code, $lot_no);
            $villagedata = $this->MisModel->getVillageName($dist_code, $subdiv_code, $circle_code, $mouza_code, $lot_no, $vill_code);

            $data['namedata'] = array_merge($districtdata, $subdivdata, $circledata, $mouzadata, $lotdata, $villagedata);

            $data['record'] = $this->db->query(
                "SELECT cb.dag_no, cb.patta_no, cb.dag_area_b, cb.dag_area_k, cb.dag_area_lc, cb.dag_area_g, cb.dag_area_are, cb.dag_revenue, cb.dag_local_tax, t1.patta_type, t2.land_type 
                                            FROM chitha_basic cb 
                                            JOIN patta_code t1 ON cb.patta_type_code = t1.type_code 
                                            JOIN landclass_code t2 ON cb.land_class_code = t2.class_code 
                                            WHERE cb.dist_code = ? 
                                            AND cb.subdiv_code = ? 
                                            AND cb.cir_code = ? 
                                            AND cb.mouza_pargona_code = ? 
                                            AND cb.lot_no = ? 
                                            AND cb.vill_townprt_code = ? 
                                            AND cb.dag_no = ?",
                [$dist_code, $subdiv_code, $circle_code, $mouza_code, $lot_no, $vill_code, $dag_no]
            )->result();

            $sql = "SELECT cp.pdar_id, cp.pdar_name, cp.pdar_father, cdp.dag_por_b,cdp.dag_por_k,cdp.dag_por_lc,cdp.dag_por_g,cdp.pdar_land_acre 
                FROM chitha_pattadar cp 
                JOIN chitha_dag_pattadar cdp ON cp.dist_code = cdp.dist_code 
                AND cp.subdiv_code = cdp.subdiv_code 
                AND cp.cir_code = cdp.cir_code 
                AND cp.mouza_pargona_code = cdp.mouza_pargona_code 
                AND cp.lot_no = cdp.lot_no 
                AND cp.vill_townprt_code = cdp.vill_townprt_code 
                AND cp.patta_no = cdp.patta_no 
                AND cp.patta_type_code = cdp.patta_type_code 
                AND cp.pdar_id = cdp.pdar_id 
                WHERE cp.dist_code = ? 
                AND cp.subdiv_code = ? 
                AND cp.cir_code = ? 
                AND cp.mouza_pargona_code = ? 
                AND cp.lot_no = ? 
                AND cp.vill_townprt_code = ? 
                AND cp.patta_no = ? 
                AND cp.patta_type_code = ? 
                AND cdp.dag_no = ? 
                ORDER BY cp.pdar_id ASC";

            $data['pattadars'] = $this->db->query($sql, [$dist_code, $subdiv_code, $circle_code, $mouza_code, $lot_no, $vill_code, $patta_no, $patta_type_code, $dag_no])->result();

            $data['tenants'] = $this->db->query(
                "SELECT ct.tenant_name, ct.tenants_father, ct.khatian_no,ct.tenant_id, tt.tenant_type 
                                             FROM chitha_tenant ct 
                                             JOIN tenant_type tt ON ct.type_of_tenant = tt.type_code 
                                             WHERE ct.dist_code = ? 
                                             AND ct.subdiv_code = ? 
                                             AND ct.cir_code = ? 
                                             AND ct.mouza_pargona_code = ? 
                                             AND ct.lot_no = ? 
                                             AND ct.vill_townprt_code = ? 
                                             AND ct.dag_no = ?",
                [$dist_code, $subdiv_code, $circle_code, $mouza_code, $lot_no, $vill_code, $dag_no]
            )->result();

            $data['addhaar_consent_content'] = self::AADHAAR_CONSENT_CONTENT;
            $data['aadhaar_consent_checkbox_text'] = self::AADHAAR_CONSENT_CHECKBOX_TEXT;

            $data['relname'] = $this->Chithamodel->relation();
            $data['base'] = $this->config->item('base_url');
            $data['signURL'] = base_url('index.php/verification/LMController/getBaseSFile');
            // $data['verify_check_url'] = base_url('index.php/LMController/isVerified/' . $dist_code .'/'. $subdiv_code . '/' . $circle_code . '/' . $mouza_code . '/' . $lot_no . '/' . $vill_code . '/' . $dag_no);
            $data['_view'] = 'verification/view_dag_details';

            $this->load->view('layout/layout', $data);
        } else {
            $this->session->set_flashdata('message', "Data Doesn't Exist for provided Data !!");
            redirect(base_url() . "index.php/verification/LMController/index");
        }
    }

    // public function isVerified($dist_code, $subdiv_code, $cir_code, $mouza_code, $lot_no, $village, $dag_no){
    //     $query = "select * from verified_dags where dist_code=? and subdiv_code=? and cir_code=? and mouza_pargona_code=? and lot_no=? and vill_townprt_code=? and dag_no=? and (signed_by_lm IS NULL or signed_by_lm = '')";

    //     $verified_dag = $this->db->query($query, [$dist_code, $subdiv_code, $cir_code, $mouza_code, $lot_no, $village, $dag_no])->result();

    //     $response = [
    //         'success' => true,
    //         'is_verified' => $verified_dag ? true : false
    //     ];

    //     echo json_encode($response);

    //     return ;

    // }

    public function getBaseSFile()
    {
        if (!isset($_POST['dist_code']) || !isset($_POST['subdiv_code']) || !isset($_POST['cir_code']) || !isset($_POST['mouza_pargona_code']) || !isset($_POST['lot_no']) || !isset($_POST['vill_townprt_code']) || !isset($_POST['patta_type_code']) || !isset($_POST['dag_no']) || $_POST['dist_code'] == '' || $_POST['subdiv_code'] == '' || $_POST['cir_code'] == '' || $_POST['mouza_pargona_code'] == '' || $_POST['lot_no'] == '' || $_POST['vill_townprt_code'] == '' || $_POST['patta_type_code'] == '' || $_POST['dag_no'] == '' || $_POST['accept_consent'] == '') {
            $response = [
                'status' => 'FAILED',
                'responseType' => 1,
                'msg' => 'The required parameters are empty!'
            ];
            echo json_encode($response);
            exit();
        }
        if (!$this->session->userdata('user_code') || $this->session->userdata('dist_code') != $_POST['dist_code'] || $this->session->userdata('subdiv_code') != $_POST['subdiv_code'] || $this->session->userdata('cir_code') != $_POST['cir_code'] || $this->session->userdata('mouza_pargona_code') != $_POST['mouza_pargona_code'] || $this->session->userdata('lot_no') != $_POST['lot_no']) {
            $response = [
                'status' => 'FAILED',
                'responseType' => 1,
                'msg' => 'User not authorized!'
            ];
            echo json_encode($response);
            exit();
        }
        $dist_code = $this->input->post("dist_code");
        $subdiv_code = $this->input->post("subdiv_code");
        $cir_code = $this->input->post("cir_code");
        $mouza_pargona_code = $this->input->post("mouza_pargona_code");
        $lot_no = $this->input->post("lot_no");
        $vill_townprt_code = $this->input->post("vill_townprt_code");
        $patta_no = $this->input->post("patta_no");
        $patta_type_code = $this->input->post("patta_type_code");
        $dag_no = $this->input->post("dag_no");

        $this->dataswitch();

        $this->db->trans_begin();

        $dist_name = $this->utilityclass->getDistrictName($dist_code);
        $subdiv_name = $this->utilityclass->getSubDivName($dist_code, $subdiv_code);
        $cir_name = $this->utilityclass->getCircleName($dist_code, $subdiv_code, $cir_code);
        $mouza_pargona_name = $this->utilityclass->getMouzaName($dist_code, $subdiv_code, $cir_code, $mouza_pargona_code);
        $lot_name = $this->utilityclass->getLotLocationName($dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no);
        $vill_townprt_name = $this->utilityclass->getVillageName($dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no, $vill_townprt_code);

        // $uuid = $this->utilityclass->getUuid($dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no, $vill_townprt_code);

        $dag_no_int = $this->db->query("SELECT dag_no_int FROM chitha_basic WHERE dist_code=? AND subdiv_code=? AND cir_code=? AND mouza_pargona_code=? AND lot_no=? AND vill_townprt_code=? AND dag_no=?", [$dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no, $vill_townprt_code, $dag_no])->row()->dag_no_int;

        $secondSelection = array('patta_code' => $patta_type_code, 'dag_no_lower' => $dag_no_int, 'dag_no_upper' => $dag_no_int);
        $data['location'] = array('dist' => trim($dist_name), 'sub' => trim($subdiv_name), 'cir' => $cir_name, 'mouza' => $mouza_pargona_name, 'lot' => $lot_name, 'vill' => $vill_townprt_name);
        $this->load->model('chitha/DharChithaModel');
        $pattatype['chithaPattatypeinfo'] = $this->DharChithaModel->getpattatype($patta_type_code);
        $chithainfo1['data'] = $this->DharChithaModel->getchithaDetailsALL($dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no, $vill_townprt_code, $dag_no_int, $dag_no_int);

        $maindataforchitha = array_merge($data, $secondSelection, $chithainfo1, $pattatype);

        $maindataforchitha['single_dag'] = '1';
        $maindataforchitha['uuid'] = $uuid = $this->db->query("select uuid from location where dist_code=? and subdiv_code=? and cir_code=? and mouza_pargona_code=? and lot_no=? and vill_townprt_code=?", [$dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no, $vill_townprt_code])->row();

        $this->load->helper('language');

        $district_code = $this->session->userdata('dist_code');
        if (in_array($district_code, BARAK_VALLEY)) {
            $this->lang->load("bengali", "bengali");
        } else {
            $this->lang->load("assamese", "assamese");
        }
        $maindataforchitha['dag_no_original'] = [];
        foreach ($maindataforchitha['data'] as $key => $value) {
            $maindataforchitha['dag_no_original'][] = $value['dag_no'];
        }

        $maindataforchitha['uuid'] = ['uuid' => $uuid->uuid];

        $content = $this->load->view('chitha_report/setChithaReport', $maindataforchitha, true);

        // echo '<pre>';
        // var_dump($content);
        // die();

        ini_set("pcre.backtrack_limit", "500000000");
        ini_set('max_execution_time', '0');
        include 'vendor/mpdf/vendor/autoload.php';
        $mpdf = new \Mpdf\Mpdf([
            'default_font_size' => 9,
            'default_font' => 'dejavusans',
            'orientation' => 'P',
            'format' => 'A4',
        ]);

        $sub_folder = $dist_code . '_' . $subdiv_code . '_' . $cir_code . '_' . $mouza_pargona_code . '_' . $lot_no . '_' . $vill_townprt_code;
        $file_name = $dist_code . '_' . $subdiv_code . '_' . $cir_code . '_' . $mouza_pargona_code . '_' . $lot_no . '_' . $vill_townprt_code . '_' . $dag_no_int;

        // mkdir(BARAK_VALLEY_CHITHA_PDF_DIR . $sub_folder, 0777, true);
        if ((!file_exists(BARAK_VALLEY_CHITHA_FRESH_PDF_DIR . $sub_folder) == true)) {
            mkdir(BARAK_VALLEY_CHITHA_FRESH_PDF_DIR . $sub_folder, 0777, true);
        }


        // $mpdf->simpleTables = true;
        // $mpdf->packTableData = true;
        $mpdf->autoScriptToLang = true;
        $mpdf->autoLangToFont = true;
        $mpdf->shrink_tables_to_fit = 1;
        $mpdf->use_kwt = true;
        $mpdf->writeHTML($content);
        // header('Content-type: application/pdf');
        ob_clean();
        // $mpdf->Output(BARAK_VALLEY_CHITHA_PDF_DIR . $sub_folder . '/' . $file_name . '.pdf', 'F');
        $mpdf->Output(BARAK_VALLEY_CHITHA_FRESH_PDF_DIR . $sub_folder . '/' . $file_name . '.pdf', 'F');



        // echo '<pre>';
        // var_dump(ESIGN_ROOT_DIRECTORY_CON);
        // die();

        if (file_exists(BARAK_VALLEY_CHITHA_FRESH_PDF_DIR . $sub_folder . '/' . $file_name . '.pdf')) {
            $pdfData = file_get_contents(BARAK_VALLEY_CHITHA_FRESH_PDF_DIR . $sub_folder . '/' . $file_name . '.pdf');
            // $this->db->where(['dist_code'=>$dist_code, 'subdiv_code'=>$subdiv_code, 'cir_code'=>$cir_code, 'mouza_pargona_code'=>$mouza_pargona_code, 'lot_no'=>$lot_no, 'vill_townprt_code'=>$vill_townprt_code, 'dag_no'=>$dag_no]);
            $check = $this->db->query('SELECT * FROM verified_dags WHERE dist_code=? AND subdiv_code=? AND cir_code=? AND mouza_pargona_code=? AND lot_no=? AND vill_townprt_code=? AND dag_no=?', [$dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no, $vill_townprt_code, $dag_no])->row();
            if (empty($check)) {
                $consentsArr = [
                    'LM' => [
                        'consent_content' => self::AADHAAR_CONSENT_CONTENT,
                        'consent_checkbox_text' => self::AADHAAR_CONSENT_CHECKBOX_TEXT,
                    ],
                    'SK' => [],
                    'CO' => [],
                    'ADC' => [],
                    'DC' => [],
                ];
                //insert
                $insertData = [
                    'dist_code' => $dist_code,
                    'subdiv_code' => $subdiv_code,
                    'cir_code' => $cir_code,
                    'mouza_pargona_code' => $mouza_pargona_code,
                    'lot_no' => $lot_no,
                    'vill_townprt_code' => $vill_townprt_code,
                    'dag_no' => $dag_no,
                    'uuid' => $uuid->uuid,
                    'signed_doc' => ($sub_folder . '/' . $file_name . '.pdf'),
                    'consents' => json_encode($consentsArr)
                ];
                $status = $this->db->insert('verified_dags', $insertData);
            } else {
                //update
                $existing_consent = json_decode($check->consents);
                $existing_consent = (array) $existing_consent;
                $existing_consent['LM'] = [
                    'consent_content' => self::AADHAAR_CONSENT_CONTENT,
                    'consent_checkbox_text' => self::AADHAAR_CONSENT_CHECKBOX_TEXT,
                ];
                $updateData = [
                    // 'uuid'=>$uuid->uuid,
                    'signed_doc' => ($sub_folder . '/' . $file_name . '.pdf'),
                    'consents' => json_encode($existing_consent)
                ];
                $this->db->where(['dist_code' => $dist_code, 'subdiv_code' => $subdiv_code, 'cir_code' => $cir_code, 'mouza_pargona_code' => $mouza_pargona_code, 'lot_no' => $lot_no, 'vill_townprt_code' => $vill_townprt_code, 'dag_no' => $dag_no]);
                $status = $this->db->update('verified_dags', $updateData);
            }
            // $dynamic_file_path = $file_name . '/' . $file_name . '.pdf';

            if ($status && $this->db->affected_rows() == 1) {
                define('ESIGN_ROOT_DIRECTORY_CON', base_url() . 'esign/');
                // $user = $this->db->query("SELECT use_name FROM loginuser_table WHERE dist_code=? AND subdiv_code=? AND cir_code=? AND mouza_pargona_code=? AND lot_no=? AND user_code=?", [$dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no, $this->session->userdata('user_code')])->row();
                $user = $this->db->query("SELECT lm_name AS user_name FROM lm_code WHERE dist_code=? AND subdiv_code=? AND cir_code=? AND mouza_pargona_code=? AND lot_no=? AND lm_code=?", [$dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no, $this->session->userdata('user_code')])->row();

                $arr = [
                    'dist_code' => $dist_code,
                    'subdiv_code' => $subdiv_code,
                    'cir_code' => $cir_code,
                    'mouza_pargona_code' => $mouza_pargona_code,
                    'lot_no' => $lot_no,
                    'vill_townprt_code' => $vill_townprt_code,
                    'dag_no' => $dag_no,
                    'dag_no_int' => $dag_no_int,
                    // 'user_name'=> translateAssToEng($user->use_name),
                    'sign_users' => [
                        'lm' => [
                            'user_name' => translateAssToEng($user->user_name),
                            'date_of_sign' => date('Y-m-d'),
                            'time_of_sign' => date('H:i:s')
                        ]
                    ],
                    'user_code' => $this->session->userdata('user_code'),
                    'user_desig_code' => $this->session->userdata('user_desig_code')
                ];
                $param = urlencode(base64_encode(openssl_encrypt(json_encode($arr), "AES-128-CTR", "singleENCRYPT", 0, "1234567893032221")));
                // $param = base64_encode(json_encode($arr));

                if($this->db->trans_status() == FALSE) {
                    $this->db->trans_rollback();
                    $response = [
                        'status'=>'FAILED',
                        'responseType'=>1,
                        'msg'=> 'Chitha pdf Generation Failed!'
                    ];
                    echo json_encode($response);
                    exit();
                }

                $this->db->trans_commit();

                $response = [
                    'status' => 'SUCCESS',
                    'responseType' => 0,
                    'msg' => 'Chitha Pdf Generated Successfully!',
                    'data' => [
                        'url' => ESIGN_ROOT_DIRECTORY_CON . 'index.php?param=' . $param
                        // 'url'=>ESIGN_ROOT_DIRECTORY_CON . 'index.php/' . $dist_code . '/' . $subdiv_code . '/' . $cir_code . '/' . $mouza_pargona_code . '/' . $lot_no . '/' . $vill_townprt_code . '/' . $dag_no,
                        // 'dist_code'=>$dist_code,
                        // 'subdiv_code'=>$subdiv_code,
                        // 'cir_code'=>$cir_code,
                        // 'mouza_pargona_code'=>$mouza_pargona_code,
                        // 'lot_no'=>$lot_no,
                        // 'vill_townprt_code'=>$vill_townprt_code,
                        // 'dag_no'=>$dag_no
                    ]
                ];
                echo json_encode($response);
                exit();
            } else {
                $this->db->trans_rollback();
                $response = [
                    'status' => 'FAILED',
                    'responseType' => 1,
                    'msg' => 'Chitha pdf Generation Failed!'
                ];
                echo json_encode($response);
                exit();
            }

            
        }

        $this->db->trans_rollback();
        $response = [
            'status' => 'FAILED',
            'responseType' => 1,
            'msg' => 'Chitha Pdf Generation Failed!'
        ];

        echo json_encode($response);
        exit();
    }

    private function generateAllDagPdf($dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no, $vill_townprt_code, $patta_type_code, $dag_no)
    {
        $this->dataswitch();
        $this->db->trans_begin();
        $dist_name = $this->utilityclass->getDistrictName($dist_code);
        $subdiv_name = $this->utilityclass->getSubDivName($dist_code, $subdiv_code);
        $cir_name = $this->utilityclass->getCircleName($dist_code, $subdiv_code, $cir_code);
        $mouza_pargona_name = $this->utilityclass->getMouzaName($dist_code, $subdiv_code, $cir_code, $mouza_pargona_code);
        $lot_name = $this->utilityclass->getLotLocationName($dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no);
        $vill_townprt_name = $this->utilityclass->getVillageName($dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no, $vill_townprt_code);

        // $uuid = $this->utilityclass->getUuid($dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no, $vill_townprt_code);

        $dag_no_int = $this->db->query("SELECT dag_no_int FROM chitha_basic WHERE dist_code=? AND subdiv_code=? AND cir_code=? AND mouza_pargona_code=? AND lot_no=? AND vill_townprt_code=? AND dag_no=?", [$dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no, $vill_townprt_code, $dag_no])->row()->dag_no_int;

        $secondSelection = array('patta_code' => $patta_type_code, 'dag_no_lower' => $dag_no_int, 'dag_no_upper' => $dag_no_int);
        $data['location'] = array('dist' => trim($dist_name), 'sub' => trim($subdiv_name), 'cir' => $cir_name, 'mouza' => $mouza_pargona_name, 'lot' => $lot_name, 'vill' => $vill_townprt_name);
        $this->load->model('chitha/DharChithaModel');
        $pattatype['chithaPattatypeinfo'] = $this->DharChithaModel->getpattatype($patta_type_code);
        $chithainfo1['data'] = $this->DharChithaModel->getchithaDetailsALL($dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no, $vill_townprt_code, $dag_no_int, $dag_no_int);

        $maindataforchitha = array_merge($data, $secondSelection, $chithainfo1, $pattatype);

        $maindataforchitha['single_dag'] = '1';
        $maindataforchitha['uuid'] = $uuid = $this->db->query("select uuid from location where dist_code=? and subdiv_code=? and cir_code=? and mouza_pargona_code=? and lot_no=? and vill_townprt_code=?", [$dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no, $vill_townprt_code])->row();

        $this->load->helper('language');

        $district_code = $this->session->userdata('dist_code');
        if (in_array($district_code, BARAK_VALLEY)) {
            $this->lang->load("bengali", "bengali");
        } else {
            $this->lang->load("assamese", "assamese");
        }
        $maindataforchitha['dag_no_original'] = [];
        foreach ($maindataforchitha['data'] as $key => $value) {
            $maindataforchitha['dag_no_original'][] = $value['dag_no'];
        }

        $maindataforchitha['uuid'] = ['uuid' => $uuid->uuid];

        $content = $this->load->view('chitha_report/setChithaReport', $maindataforchitha, true);

        // echo '<pre>';
        // var_dump($content);
        // die();

        ini_set("pcre.backtrack_limit", "500000000");
        ini_set('max_execution_time', '0');
        include 'vendor/mpdf/vendor/autoload.php';
        $mpdf = new \Mpdf\Mpdf([
            'default_font_size' => 9,
            'default_font' => 'dejavusans',
            'orientation' => 'P',
            'format' => 'A4',
        ]);

        $sub_folder = $dist_code . '_' . $subdiv_code . '_' . $cir_code . '_' . $mouza_pargona_code . '_' . $lot_no . '_' . $vill_townprt_code;
        $file_name = $dist_code . '_' . $subdiv_code . '_' . $cir_code . '_' . $mouza_pargona_code . '_' . $lot_no . '_' . $vill_townprt_code . '_' . $dag_no_int;

        // mkdir(BARAK_VALLEY_CHITHA_PDF_DIR . $sub_folder, 0777, true);
        if (!file_exists(BARAK_VALLEY_CHITHA_FRESH_PDF_DIR . $sub_folder)) {
            mkdir(BARAK_VALLEY_CHITHA_FRESH_PDF_DIR . $sub_folder, 0777, true);
        }


        // $mpdf->simpleTables = true;
        // $mpdf->packTableData = true;
        $mpdf->autoScriptToLang = true;
        $mpdf->autoLangToFont = true;
        $mpdf->shrink_tables_to_fit = 1;
        $mpdf->use_kwt = true;
        $mpdf->writeHTML($content);
        // header('Content-type: application/pdf');
        ob_clean();
        // $mpdf->Output(BARAK_VALLEY_CHITHA_PDF_DIR . $sub_folder . '/' . $file_name . '.pdf', 'F');
        $mpdf->Output(BARAK_VALLEY_CHITHA_FRESH_PDF_DIR . $sub_folder . '/' . $file_name . '.pdf', 'F');



        // echo '<pre>';
        // var_dump(ESIGN_ROOT_DIRECTORY_CON);
        // die();

        if (file_exists(BARAK_VALLEY_CHITHA_FRESH_PDF_DIR . $sub_folder . '/' . $file_name . '.pdf')) {
            $pdfData = file_get_contents(BARAK_VALLEY_CHITHA_FRESH_PDF_DIR . $sub_folder . '/' . $file_name . '.pdf');
            // $this->db->where(['dist_code'=>$dist_code, 'subdiv_code'=>$subdiv_code, 'cir_code'=>$cir_code, 'mouza_pargona_code'=>$mouza_pargona_code, 'lot_no'=>$lot_no, 'vill_townprt_code'=>$vill_townprt_code, 'dag_no'=>$dag_no]);
            $check = $this->db->query('SELECT * FROM verified_dags WHERE dist_code=? AND subdiv_code=? AND cir_code=? AND mouza_pargona_code=? AND lot_no=? AND vill_townprt_code=? AND dag_no=?', [$dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no, $vill_townprt_code, $dag_no])->row();
            if (empty($check)) {
                $consentsArr = [
                    'LM' => [
                        'consent_content' => self::AADHAAR_CONSENT_CONTENT,
                        'consent_checkbox_text' => self::AADHAAR_CONSENT_CHECKBOX_TEXT,
                    ],
                    'SK' => [],
                    'CO' => [],
                    'ADC' => [],
                    'DC' => [],
                ];
                //insert
                $insertData = [
                    'dist_code' => $dist_code,
                    'subdiv_code' => $subdiv_code,
                    'cir_code' => $cir_code,
                    'mouza_pargona_code' => $mouza_pargona_code,
                    'lot_no' => $lot_no,
                    'vill_townprt_code' => $vill_townprt_code,
                    'dag_no' => $dag_no,
                    'uuid' => $uuid->uuid,
                    'signed_by_lm' => $this->session->userdata('user_code'),
                    'date_of_sign_lm' => date('Y-m-d H:i:s'),
                    'token' => json_encode(['LM' => '', 'SK' => '', 'CO' => '', 'ADC' => '', 'DC' => '']),
                    'signed_doc' => ($sub_folder . '/' . $file_name . '.pdf'),
                    'consents' => json_encode($consentsArr)
                ];
                $status = $this->db->insert('verified_dags', $insertData);
            } else {
                //update
                $existing_consent = json_decode($check->consents);
                $existing_consent = (array) $existing_consent;
                $existing_consent['LM'] = [
                    'consent_content' => self::AADHAAR_CONSENT_CONTENT,
                    'consent_checkbox_text' => self::AADHAAR_CONSENT_CHECKBOX_TEXT,
                ];
                $updateData = [
                    // 'uuid'=>$uuid->uuid,
                    'signed_doc' => ($sub_folder . '/' . $file_name . '.pdf'),
                    'consents' => json_encode($existing_consent)
                ];
                $this->db->where(['dist_code' => $dist_code, 'subdiv_code' => $subdiv_code, 'cir_code' => $cir_code, 'mouza_pargona_code' => $mouza_pargona_code, 'lot_no' => $lot_no, 'vill_townprt_code' => $vill_townprt_code, 'dag_no' => $dag_no]);
                $status = $this->db->update('verified_dags', $updateData);
            }
            // $dynamic_file_path = $file_name . '/' . $file_name . '.pdf';

            if(!$status || $this->db->affected_rows() < 1) {
                $this->db->trans_rollback();
                // exit();
            }

            if($this->db->trans_status() == FALSE) {
                $this->db->trans_rollback();
                // exit();
            }

            $this->db->trans_commit();
            // exit();
        }

        $this->db->trans_rollback();
        // exit();
    }

    public function verificationCertificate()
    {
        $dist_code = $this->session->userdata('dcode');
        $user_code = $this->session->userdata('user_code');
        $subdiv_code = $this->session->userdata('subdiv_code');
        $cir_code = $this->session->userdata('cir_code');
        $mouza_pargona_code = $this->session->userdata('mouza_pargona_code');
        $lot_no = $this->session->userdata('lot_no');

        $this->dataswitch();
        
        $data = $this->getVerificationCertificateData();

        $chitha_verification_certificate = $this->db->where('dist_code', $dist_code)
                                                ->where('subdiv_code', $subdiv_code)
                                                ->where('cir_code', $cir_code)
                                                ->where('mouza_pargona_code', $mouza_pargona_code)
                                                ->where('lot_no', $lot_no)
                                                ->where('user_desig_code', 'LM')
                                                ->get('chitha_verification_certificates')
                                                ->row();
        
        $data['chitha_verification_certificate'] = null;
        if($chitha_verification_certificate){
            if(!$chitha_verification_certificate->signed_by || !$chitha_verification_certificate->signed_file_name){
                $this->db->where('id', $chitha_verification_certificate->id)->delete('chitha_verification_certificates');
                unlink(VERIFICATION_CERTICATE_ESIGN_PATH . $chitha_verification_certificate->file_name);
            }else{
                $data['chitha_verification_certificate'] = $chitha_verification_certificate;
            }
        }

        $data['addhaar_consent_content'] = self::AADHAAR_CONSENT_CONTENT;
        $data['aadhaar_consent_checkbox_text'] = self::AADHAAR_CONSENT_CHECKBOX_TEXT;

        $data['_view'] = 'verification/lm/certificate';
        
        $this->load->view('layout/layout', $data);
    }

    public function eSignInit(){
        $dist_code = $this->session->userdata('dcode');
        $subdiv_code = $this->session->userdata('subdiv_code');
        $cir_code = $this->session->userdata('cir_code');
        $mouza_pargona_code = $this->session->userdata('mouza_pargona_code');
        $lot_no = $this->session->userdata('lot_no');

        $this->dataswitch();

        $user = $this->db->query("SELECT lm_name AS user_name FROM lm_code WHERE dist_code=? AND subdiv_code=? AND cir_code=? AND mouza_pargona_code=? AND lot_no=? AND lm_code=?", [$dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no, $this->session->userdata('user_code')])->row();
        $lm_name = $user->user_name;

        if($lm_name != ''){
            $translate = translateAssToEng($lm_name);
            if(!$translate['success']){
                $response = [
                    'status'=>'FAILED',
                    'responseType'=>1,
                    'msg'=> $translate['message']
                ];
                echo json_encode($response);
                exit();
            }else{
                $lm_name = $translate['message'];
            }
        }
        
        $check_chitha_verification_certificate = $this->db->where('dist_code', $dist_code)
                                                    ->where('subdiv_code', $subdiv_code)
                                                    ->where('cir_code', $cir_code)
                                                    ->where('mouza_pargona_code', $mouza_pargona_code)
                                                    ->where('lot_no', $lot_no)
                                                    ->where('user_desig_code', 'LM')
                                                    ->get('chitha_verification_certificates')
                                                    ->row();
        
        if($check_chitha_verification_certificate){
            if($check_chitha_verification_certificate->signed_file_name){
                $response = [
                    'status' => 'FAILED',
                    'responseType' => 1,
                    'msg' => 'Certificate has already been signed'
                ];
        
                echo json_encode($response);
                return;
            }

            $file_name = $check_chitha_verification_certificate->file_name;
        }else{
            if ((!file_exists(VERIFICATION_CERTICATE_ESIGN_PATH) == true)) {
                mkdir(VERIFICATION_CERTICATE_ESIGN_PATH, 0777, true);
            }
            
            $this->db->trans_begin();

            $file_name = $dist_code . '_' . $subdiv_code . '_' . $cir_code . '_' .$mouza_pargona_code . '_' . $lot_no . '_LM_' . uniqid() . '.pdf';
    
            $data = $this->getVerificationCertificateData();
    
            $this->load->helper('language');
    
            $html = $this->load->view('verification/lm/certificate-partials', $data, TRUE);
            
            ini_set("pcre.backtrack_limit", "500000000");
            ini_set('max_execution_time', '0');
            include 'vendor/mpdf/vendor/autoload.php';
    
            $mpdf = new \Mpdf\Mpdf([
                'default_font_size' => 11,
                'default_font' => 'dejavusans',
                'orientation' => 'P',
                'format' => 'A4',
            ]);
    
            $mpdf->autoScriptToLang = true;
            $mpdf->autoLangToFont = true;
            $mpdf->shrink_tables_to_fit = 1;
            $mpdf->use_kwt = true;
    
            $mpdf->WriteHTML($html);
    
            // Or save to a file
            $mpdf->Output(VERIFICATION_CERTICATE_ESIGN_PATH . $file_name, \Mpdf\Output\Destination::FILE);
            
            $consentsArr = [
                                'consent_content' => self::AADHAAR_CONSENT_CONTENT,
                                'consent_checkbox_text' => self::AADHAAR_CONSENT_CHECKBOX_TEXT,
                            ];
    
            $data = [
                'dist_code' => $dist_code,
                'subdiv_code' => $subdiv_code,
                'cir_code' => $cir_code,
                'mouza_pargona_code' => $mouza_pargona_code,
                'lot_no' => $lot_no,
                'user_desig_code' => 'LM',
                'file_name' => $file_name,
                'consents' => json_encode($consentsArr),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ];
            // chitha_verification_certificates
            $status = $this->db->insert('chitha_verification_certificates', $data);
            if($status){
                $this->db->trans_commit();
            }else{
                $this->db->trans_rollback();
                log_message('error', '#ERRVERCERT0001: Last Query => ' . $this->db->last_query());
                $response = [
                    'status' => 'FAILED',
                    'responseType' => 1,
                    'msg' => '#ERRVERCERT0001: Something went wrong. Please try again later.'
                ];
                echo json_encode($response);
                exit();
            }
            
        }
        
        define('ESIGN_ROOT_DIRECTORY_CON', base_url() . 'esign/');

        // $user = $this->db->query("SELECT lm_name AS user_name FROM lm_code WHERE dist_code=? AND subdiv_code=? AND cir_code=? AND mouza_pargona_code=? AND lot_no=? AND lm_code=?", [$dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no, $this->session->userdata('user_code')])->row();

        $arr = [
            'dist_code' => $dist_code,
            'subdiv_code' => $subdiv_code,
            'cir_code' => $cir_code,
            'mouza_pargona_code' => $mouza_pargona_code,
            'lot_no' => $lot_no,
            'sign_users' => [
                'lm' => [
                    'user_name' => $lm_name,
                    'date_of_sign' => date('Y-m-d'),
                    'time_of_sign' => date('H:i:s')
                ]
            ],
            'file_name' => $file_name,
            'user_code' => $this->session->userdata('user_code'),
            'user_desig_code' => $this->session->userdata('user_desig_code'),
            'redirect' => 'verification/LMController/verificationCertificate',
            'is_final' => '0'
        ];
        $param = urlencode(base64_encode(openssl_encrypt(json_encode($arr), "AES-128-CTR", "singleENCRYPT", 0, "1234567893032221")));

        $response = [
            'status' => 'SUCCESS',
            'responseType' => 0,
            'msg' => 'Verification certificate is ready to sign',
            'data' => [
                'url' => ESIGN_ROOT_DIRECTORY_CON . 'verify_chitha_certificate/index.php?param=' . $param
                // 'dist_code'=>$dist_code,
                // 'subdiv_code'=>$subdiv_code,
                // 'cir_code'=>$cir_code,
                // 'mouza_pargona_code'=>$mouza_pargona_code,
                // 'lot_no'=>$lot_no,
                // 'vill_townprt_code'=>$vill_townprt_code,
            ]
        ];
        echo json_encode($response);
        exit();
        
    }

    private function getVerificationCertificateData(){
        $dist_code = $this->session->userdata('dcode');
        $user_code = $this->session->userdata('user_code');
        $this->load->model('verification/VerificationModel');

        $subdiv_code = $this->session->userdata('subdiv_code');
        $cir_code = $this->session->userdata('cir_code');
        $mouza_pargona_code = $this->session->userdata('mouza_pargona_code');
        $lot_no = $this->session->userdata('lot_no');

        $district = $this->db->query("SELECT loc_name, locname_eng FROM location WHERE dist_code=? AND subdiv_code=?", [$dist_code,'00'])->row();
        $dist_name = $district->loc_name . ' (' . $district->locname_eng . ')';
        $data['dist_name'] = $dist_name;

        $circle = $this->db->query("SELECT loc_name, locname_eng FROM location WHERE dist_code=? AND subdiv_code=? AND cir_code=? AND mouza_pargona_code=?", [$dist_code,$subdiv_code,$cir_code,'00'])->row();
        $circle_name = $circle->loc_name . ' (' . $circle->locname_eng . ')';
        $data['circle_name'] = $circle_name;
        
        $mouza = $this->db->query("SELECT loc_name, locname_eng, uuid FROM location WHERE dist_code=? AND subdiv_code=? AND cir_code=? AND mouza_pargona_code=? AND lot_no=?", [$dist_code, $subdiv_code, $cir_code, $mouza_pargona_code,'00'])->row();
        $mouza_name = $mouza->loc_name . ' (' . $mouza->locname_eng . ')';
        $data['mouza_name'] = $mouza_name;

        $lot = $this->db->query("SELECT loc_name, locname_eng, uuid FROM location WHERE dist_code=? AND subdiv_code=? AND cir_code=? AND mouza_pargona_code=? AND lot_no=? AND vill_townprt_code=?", [$dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no,'00000'])->row();
        $lot_name = $lot->loc_name . ' (' . $lot->locname_eng . ')';
        $data['lot_name'] = $lot_name;

        $villages = $this->VerificationModel->getVillages();
        $data['lm_name'] = $this->db->query("SELECT lm_name FROM lm_code WHERE dist_code=? AND subdiv_code=? AND cir_code=? AND mouza_pargona_code=? AND lot_no=? AND lm_code=?",[$dist_code, $subdiv_code, $cir_code, $mouza_pargona_code,$lot_no,$user_code])->row()->lm_name;
        $data['villages'] = $villages;

        return $data;
    }

    public function viewSignedPdf()
    {
        $user_desig_code = $this->session->userdata('user_desig_code');
        $dist_code = $this->session->userdata('dcode');
        if ($user_desig_code == 'CO' || $user_desig_code == 'SK' || $user_desig_code == 'LM') {
            $subdiv_code = $this->session->userdata('subdiv_code');
            $cir_code = $this->session->userdata('cir_code');
        }
        if ($user_desig_code == 'LM') {
            $mouza_pargona_code = $this->session->userdata('mouza_pargona_code');
            $lot_no = $this->session->userdata('lot_no');
        }



        $this->dataswitch();

        if ($user_desig_code == 'DC' || $user_desig_code == 'ADC') {
            $villages = $this->db->query("SELECT loc_name, locname_eng, uuid, vill_townprt_code, cir_code, dist_code, subdiv_code FROM location WHERE dist_code=? AND subdiv_code!='00' AND cir_code!='00' AND mouza_pargona_code!='00' AND lot_no!='00' AND vill_townprt_code!='00000'", [$dist_code])->result();
        } else if ($user_desig_code == 'CO' || $user_desig_code == 'SK') {
            $villages = $this->db->query("SELECT loc_name, locname_eng, uuid, vill_townprt_code, cir_code, dist_code, subdiv_code FROM location WHERE dist_code=? AND subdiv_code=? AND cir_code=? AND mouza_pargona_code!='00' AND lot_no!='00' AND vill_townprt_code!='00000'", [$dist_code, $subdiv_code, $cir_code])->result();
        } else if ($user_desig_code == 'LM') {
            $villages = $this->db->query("SELECT loc_name, locname_eng, uuid, vill_townprt_code, cir_code, dist_code, subdiv_code FROM location WHERE dist_code=? AND subdiv_code=? AND cir_code=? AND mouza_pargona_code=? AND lot_no=? AND vill_townprt_code!='00000'", [$dist_code, $subdiv_code, $cir_code, $mouza_pargona_code, $lot_no])->result();
        }

        if (!empty($villages)) {
            foreach ($villages as $village) {
                $village->cir_name = $this->utilityclass->getCircleName($village->dist_code, $village->subdiv_code, $village->cir_code);
            }
        }

        if (isset($_POST['uuid']) && $_POST['uuid'] != '') {
            $uuid = $this->input->post('uuid');
            $location_names = $this->db->query("SELECT dist_code, subdiv_code, cir_code, mouza_pargona_code, lot_no, vill_townprt_code FROM location WHERE uuid=?", [$uuid])->row();
        } else {
            $uuid = $villages[0]->uuid;
            $location_names = $this->db->query("SELECT dist_code, subdiv_code, cir_code, mouza_pargona_code, lot_no, vill_townprt_code FROM location WHERE uuid=?", [$uuid])->row();
        }

        $dist_name = $this->utilityclass->getDistrictName($location_names->dist_code);
        $subdiv_name = $this->utilityclass->getSubDivName($location_names->dist_code, $location_names->subdiv_code);
        $cir_name = $this->utilityclass->getCircleName($location_names->dist_code, $location_names->subdiv_code, $location_names->cir_code);
        $mouza_pargona_name = $this->utilityclass->getMouzaName($location_names->dist_code, $location_names->subdiv_code, $location_names->cir_code, $location_names->mouza_pargona_code);
        $lot_name = $this->utilityclass->getLotLocationName($location_names->dist_code, $location_names->subdiv_code, $location_names->cir_code, $location_names->mouza_pargona_code, $location_names->lot_no);
        $vill_townprt_name = $this->utilityclass->getVillageName($location_names->dist_code, $location_names->subdiv_code, $location_names->cir_code, $location_names->mouza_pargona_code, $location_names->lot_no, $location_names->vill_townprt_code);

        if ($user_desig_code == 'DC') {
            $verifiedDags = $this->db->query("SELECT id, dag_no, date_of_sign_lm, date_of_sign_sk, date_of_sign_co, date_of_sign_adc, date_of_sign_dc, signed_doc, uuid FROM verified_dags WHERE uuid=? AND (signed_by_dc IS NOT NULL AND signed_by_dc != '') AND (signed_doc IS NOT NULL AND signed_doc != '')", [$uuid])->result();
        } else if ($user_desig_code == 'ADC') {
            $verifiedDags = $this->db->query("SELECT id, dag_no, date_of_sign_lm, date_of_sign_sk, date_of_sign_co, date_of_sign_adc, date_of_sign_dc, signed_doc, uuid FROM verified_dags WHERE uuid=? AND (signed_by_adc IS NOT NULL AND signed_by_adc != '') AND (signed_doc IS NOT NULL AND signed_doc != '')", [$uuid])->result();
        } else if ($user_desig_code == 'CO') {
            $verifiedDags = $this->db->query("SELECT id, dag_no, date_of_sign_lm, date_of_sign_sk, date_of_sign_co, date_of_sign_adc, date_of_sign_dc, signed_doc, uuid FROM verified_dags WHERE uuid=? AND (signed_by_co IS NOT NULL AND signed_by_co != '') AND (signed_doc IS NOT NULL AND signed_doc != '')", [$uuid])->result();
        } else if ($user_desig_code == 'SK') {
            $verifiedDags = $this->db->query("SELECT id, dag_no, date_of_sign_lm, date_of_sign_sk, date_of_sign_co, date_of_sign_adc, date_of_sign_dc, signed_doc, uuid FROM verified_dags WHERE uuid=? AND (signed_by_sk IS NOT NULL AND signed_by_sk != '') AND (signed_doc IS NOT NULL AND signed_doc != '')", [$uuid])->result();
        } else if ($user_desig_code == 'LM') {
            $verifiedDags = $this->db->query("SELECT id, dag_no, date_of_sign_lm, date_of_sign_sk, date_of_sign_co, date_of_sign_adc, date_of_sign_dc, signed_doc, uuid FROM verified_dags WHERE uuid=? AND (signed_by_lm IS NOT NULL AND signed_by_lm != '') AND (signed_doc IS NOT NULL AND signed_doc != '')", [$uuid])->result();
        }

        $verified_dags = [];

        foreach ($verifiedDags as $verifiedDag) {
            if (file_exists(BARAK_VALLEY_CHITHA_PDF_DIR . $verifiedDag->signed_doc)) {
                $file_name_array = explode('/', $verifiedDag->signed_doc);
                $file_name = $file_name_array[count($file_name_array) - 1];
                $verifiedDag->param = $verifiedDag->uuid . '_' . $file_name;
                if ($user_desig_code == 'LM') {
                    $verifiedDag->sign_date = date('d-m-Y H:i:s', strtotime($verifiedDag->date_of_sign_lm));
                } else if ($user_desig_code == 'SK') {
                    $verifiedDag->sign_date = date('d-m-Y H:i:s', strtotime($verifiedDag->date_of_sign_sk));
                } else if ($user_desig_code == 'CO') {
                    $verifiedDag->sign_date = date('d-m-Y H:i:s', strtotime($verifiedDag->date_of_sign_co));
                } else if ($user_desig_code == 'ADC') {
                    $verifiedDag->sign_date = date('d-m-Y H:i:s', strtotime($verifiedDag->date_of_sign_adc));
                } else if ($user_desig_code == 'DC') {
                    $verifiedDag->sign_date = date('d-m-Y H:i:s', strtotime($verifiedDag->date_of_sign_dc));
                }
                $verified_dags[] = $verifiedDag;
            }
        }



        $data['villages'] = $villages;
        $data['location_names'] = 'District: ' . $dist_name . ', Sub-Divisional: ' . $subdiv_name . ', Circle: ' . $cir_name . ', Mouza: ' . $mouza_pargona_name . ', Lot: ' . $lot_name . ', Village: ' . $vill_townprt_name;
        $data['verified_dags'] = $verified_dags;

        if (isset($_POST['uuid']) && $_POST['uuid'] != '') {
            echo json_encode([
                'status' => 'SUCCESS',
                'responseType' => 2,
                'data' => $data
            ]);
            exit();
        } else {
            $data['_view'] = 'verification/lm/view_signed_doc';
            $this->load->view('layout/layout', $data);
        }
    }

    public function getSignedPdf()
    {
        $param = $this->input->get('param');
        $file_name_array = explode('_', $param);
        $uuid = $file_name_array[0];
        unset($file_name_array[0]);
        $file_name = implode('_', $file_name_array);

        $this->dataswitch();
        $location = $this->db->query("SELECT * FROM location WHERE uuid=?", [$uuid])->row();
        $folder = $location->dist_code . '_' . $location->subdiv_code . '_' . $location->cir_code . '_' . $location->mouza_pargona_code . '_' . $location->lot_no . '_' . $location->vill_townprt_code;

        if (file_exists(BARAK_VALLEY_CHITHA_PDF_DIR . $folder . '/' . $file_name)) {
            $file_path = BARAK_VALLEY_CHITHA_PDF_DIR . $folder . '/' . $file_name;
            $content_type = 'application/pdf';

            header('Content-Type: ' . $content_type);
            header('Content-Length: ' . filesize($file_path));
            ob_clean();
            echo file_get_contents($file_path);
        }
    }
}
